### PR TITLE
Remove duplicate change entry for #1134 for 2.1.0 (2017-05-26)

### PR DESCRIPTION
**Pull request by SoumenDass**
## What do these changes do?
Remove duplicate change entry for #1134 for 2.1.0 (2017-05-26)

## Are there changes in behavior for the user?
No

## Related issue number
https://github.com/aio-libs/aiohttp/issues/1960

## Checklist
- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [] Add a new entry to `CHANGES.rst`
  * Choose any open position to avoid merge conflicts with other PRs.
  * Add a link to the issue you are fixing (if any) using `#issue_number` format at the end of changelog message. Use Pull Request number if there are no issues for PR or PR covers the issue only partially.

### CODE REVIEW

**Comment by fafhrd91** [comment]
thanks

**Comment by SoumenDass** [comment]
I'm new at this - once the merge is commited, how does it reflect in the website? In the http://aiohttp.readthedocs.io/en/stable/changes.html#id1 page, I can still see the duplicate entries even though https://github.com/aio-libs/aiohttp/blob/master/CHANGES.rst is correct.

**Comment by fafhrd91** [comment]
it is available in "latest", it will appear in stable in next release

**Comment by SoumenDass** [comment]
thanks.

**Pull request merged**
