### PR TITLE
moving to async/await syntax

### PR DESCRIPTION
**Pull request by eteamin**
## What do these changes do?

Changed some files to use async/await syntax.

## Related issue number

issue #2343

### CODE REVIEW

**Comment by asvetlov** [comment]
I suggest not converting everything at once but create a PR per file. Tests should go first, sure.
Reviewing single file is much easier than the whole project.

I'll tune CI bots to disable 3.4 this evening

**Comment by samuelcolvin** [comment]
I understand why you say this, but doing a build for each file will take a loooong time and will also impact build times for all other aio-lib projects since travis throttles builds per organisation.

I spent about two hours yesterday waiting for aiohttp builds to finish to aiohttp-devtools builds would start.

**Comment by webknjaz** [comment]
@samuelcolvin normal push builds are relatively fast: they don't run OS X at all.

**Comment by asvetlov** [comment]
Well, a PR for a 2-3 small files is an option -- but reviewing 10000 long diff is a nightmare.
Pretty sure everybody understands it very well.

**Comment by samuelcolvin** [comment]
yes I agree, makes sense.

**Pull request closed without merging**
