### PR TITLE
Specify timeout in aiohttp.request

### PR DESCRIPTION
**Pull request by knight42**
## What do these changes do?
Enable users to set `ClientTimeout` in `aiohttp.request`

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by asvetlov** [comment]
Thank you for the contribution.
Would you reflect the change in [aiohttp documentation](https://docs.aiohttp.org/en/stable/client_reference.html#basic-api)?

**Comment by knight42** [comment]
@asvetlov Done!

**Comment by knight42** [comment]
@asvetlov @webknjaz hi! Could this be merged now?

**Comment by webknjaz** [comment]
@knight42 could you please also add a changelog fragment to `CHANGES` folder?

**Comment by knight42** [comment]
@webknjaz Done!

**Comment by webknjaz** [comment]
Thanks!

**Pull request merged**
