### PR TITLE
New-style middleware by default

### PR DESCRIPTION
**Pull request by ayushkovskiy**
NOTE: this PR is a continuation of https://github.com/aio-libs/aiohttp/pull/3574/

## What do these changes do?
These changes deprecate old-style middleware with the `@middleware` decorator.

## Are there changes in behavior for the user?
Old-style middleware will no longer work, the `@middleware` decorator still exists but is depricated.

## Related issue number
https://github.com/aio-libs/aiohttp/issues/3569

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Do we need a second pr?

I'll happily fix #3574 once someone is ready to review and merge it.

**Comment by atemate** [comment]
@samuelcolvin current PR just fixes tests and spelling mistakes of https://github.com/aio-libs/aiohttp/pull/3574

**Comment by samuelcolvin** [comment]
ok

**Comment by asvetlov** [comment]
Thank you both @samuelcolvin and @ayushkovskiy

**Pull request merged**
