### PR TITLE
Set write buffer limit to zero on client and server

### PR DESCRIPTION
**Pull request by asvetlov**
#2698

### CODE REVIEW

**Comment by fafhrd91** [comment]
You should run some benchmarks

**Comment by asvetlov** [comment]
Sure will do

**Comment by pfreixes** [comment]
@asvetlov just some general considerations, I would like to put myself int he same page as you because sure I'm missing something.

The `StreamWriter.drain` method uses the Asyncio method `_drain_helper` which checks if the stream is paused, in case that is paused will wait till the stream is resumed. Having a new limit of 0 for the high water mark - that is what this MR is doing - shouldn't we expect that the stream is never paused? Making useless the call to the drain? 

At the same time, the call to the `StreamWriter.drain` made by the `StreamWriter.write` it's at least a bit confusing IMHO - sure I'm missing something again. It calls explicitly the `drain` if the size of the buffer sent till that specific moment is greater than `0x10000`, my questions here are:

1) Why 16 bytes?
2) Why call the drain when we have sent 16 bytes?
3) Why we are not just calling the `Asyncio._drain_helper` setting the high watermark to the desired value?

**Comment by asvetlov** [comment]
Good questions. The initial idea was not using *aiohttp/asyncio buffering* but only OS kernel write buffer for a socket.
On benchmarking I see ~7% slowdown, need to investigate more.

**Pull request closed without merging**
