### PR TITLE
[backport][3.8][PR#5809] Integrate autobahn tests with pytest

### PR DESCRIPTION
**Pull request by anesabml**
## What do these changes do?

Automate running autobahn test suite.

## Are there changes in behavior for the user?

No.

## Related issue number

#4247

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by anesabml** [comment]
python-on-whales requires python 3.7 and above.

**Comment by webknjaz** [comment]
Oh, so it may need to be reimplemented with pure subprocess calls probably.

**Comment by webknjaz** [comment]
@asvetlov I'd rather not merge things into 3.8 that break tests. Especially while I'm working on recovering the broken CI.

**Comment by webknjaz** [comment]
Hotfixed by https://github.com/aio-libs/aiohttp/pull/6103.

**Pull request merged**
