### PR TITLE
Make LineTooLong exception more detailed about actual data size

### PR DESCRIPTION
**Pull request by popravich**
## What do these changes do?

Implementation of #2857 

## Are there changes in behavior for the user?

No

## Related issue number

#2857

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by asvetlov** [comment]
Looks good but tests should be fixed

**Comment by popravich** [comment]
Is it the tests should be fixed or py-parser?
Tests are failing because py-parser counts more bytes than c-parser (this issue I described in https://github.com/aio-libs/aiohttp/issues/2857#issuecomment-374603731)

**Comment by popravich** [comment]
Http Py-parser and C-parser calculate data length in a different ways.
I can either make Py-parser act like C-parser or update tests with placeholders in `LineTooLong`
messages and not check actual data size (which is reported different by Py- and C-parser).

**Comment by asvetlov** [comment]
Sorry, looks like my comment is missing.
Better to fix py-parser to be consistent with c-parser I think

**Comment by popravich** [comment]
Ok, I will update this PR

**Comment by popravich** [comment]
Updated PR.

**Comment by asvetlov** [comment]
Please merge, but add CHANGES note first.
Would you backport the PR into 3.1 branch? If yes I'll make a new release.
Backport procedure is described here: https://docs.aiohttp.org/en/latest/contributing.html#backporting

**Comment by popravich** [comment]
Ok, give me some time for this.

**Pull request merged**
