### PR TITLE
Update FAQ

### PR DESCRIPTION
**Pull request by asvetlov**
Reflect the fact that aiohttp supports route decorators now.

### CODE REVIEW

**Comment by socketpair** [comment]
Please add since which version it works.

**Comment by asvetlov** [comment]
@socketpair done

**Comment by socketpair** [comment]
Is it possible to use this decorator on top of View (http://aiohttp.readthedocs.io/en/stable/web_reference.html#view) ?

I think, it should be mentioned in both, FAQ and main doc (http://aiohttp.readthedocs.io/en/stable/web_reference.html#routetabledef). (I'm going to use it, I still did not test)

**Comment by asvetlov** [comment]
Views are not supported (yet), PR is welcome!

**Comment by socketpair** [comment]
So, it will be nice to mention, that Views are not supported yet.

**Comment by asvetlov** [comment]
I hope somebody will find a time for #2472 before 3.0
Let me merge as is.

**Pull request merged**
