### PR TITLE
Add aiomixcloud to third party users

### PR DESCRIPTION
**Pull request by amikrop**

### CODE REVIEW

**Comment by amikrop** [comment]
Thanks a lot!

**Comment by socketpair** [comment]
You forgot to add `Mixcloud` to `docs/spelling_wordlist.txt`

**Comment by amikrop** [comment]
Greetings. Regarding the "after some time period ask to raise the status" line you have on https://aiohttp.readthedocs.io/en/stable/third_party.html#others I am not quite sure about its meaning. Is it required by me (us, the pull request creators) to do something specific for the merged changes to show up on your documentation website? Thanks a lot, in advance.

**Comment by webknjaz** [comment]
@amikrop it's there, under `/en/latest` URL, not stable. Stable points to the LTS branch.

**Comment by amikrop** [comment]
I see, thanks!

**Pull request merged**
