### PR TITLE
Fix CI for 3.8

### PR DESCRIPTION
**Pull request by derlih**
## What do these changes do?

Fixes CI for 3.8 branch

## Are there changes in behavior for the user?

No

## Related issue number

No

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Review by webknjaz — CHANGES_REQUESTED** [review]
I don't think this will work long-term. I think the legacy resolver is to be removed soon.

**Comment by derlih** [comment]
I think then this issue https://github.com/jazzband/pip-tools/issues/1190 will be implemented.
Also I think we should fix the CI ASAP. Doesn't matter how.

**Comment by webknjaz** [comment]
@derlih it was agreed to use just `-r` in #5486.

**Comment by webknjaz** [comment]
Superseded by #5486.

**Pull request closed without merging**
