### PR TITLE
3.8 test run fix

### PR DESCRIPTION
**Pull request by derlih**
## What do these changes do?

Fix test run for python 3.6 on 3.8 branch

## Are there changes in behavior for the user?

no

## Related issue number

#5447 

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by derlih** [comment]
pypy run failed. It couldn't install `typed_ast` which is dependency of `mypy` and `black`.
Both of those packages are marked as `implementation_name=="cpython"` in `lint.txt'.
@webknjaz do you know why pip tries to install it?

**Comment by Dreamsorcerer** [comment]
Looks like something to do with this change @greshilov:
https://github.com/aio-libs/aiohttp/commit/e82eac848fce6fafe4cc33e74fdfc46ca4179019#diff-2676271ded3ba0170b6048b4fda0af7d5fcad17157ea8a1f217dfb505d8120a9R227

**Comment by webknjaz** [comment]
> @webknjaz do you know why pip tries to install it?

Because not all of the make targets changed `pip install` to use `-r` and `-c`: https://github.com/aio-libs/aiohttp/blob/9a09d1b/Makefile#L65 And now the file that used to have direct deps contains all the transitive deps too, without any env markers. That should be aligned with https://github.com/aio-libs/aiohttp/blob/9a09d1b/Makefile#L148.

**Review by webknjaz — APPROVED** [review]

**Comment by webknjaz** [comment]
Can anybody take care of the Makefile before we merge this in?

**Comment by Dreamsorcerer** [comment]
> Can anybody take care of the Makefile before we merge this in?

https://github.com/aio-libs/aiohttp/pull/5470
I haven't got the slightest clue what I'm doing...

**Comment by webknjaz** [comment]
Looks like #5470 fixed this in a more elegant manner.

**Comment by derlih** [comment]
@webknjaz 
#5470 changes only dependency installation, but not type fixes for python 3.6

**Comment by Dreamsorcerer** [comment]
I think he meant #5466, which seemed to be enough when I tried it. Once CI is back up, I'll double check and also deal with updating mypy to the latest release.

**Pull request closed without merging**
