### PR TITLE
Make exceptions pickleable.

### LINKED ISSUE #4077: ClientConnectionError exception doesn't serialize properly
## Long story short

`ClientConnectionError` exception doesn't serialize propertly

## Expected behaviour

To be able to add `ClientConnectError` to a queue and get it back.

## Actual behaviour

`AttributeError: 'str' object has no attribute 'errno'`

## Steps to reproduce

A similar issue is reproducible using the following code snippet:

```
import aiohttp
import pickle


connection_key = aiohttp.client_reqrep.ConnectionKey
ose = OSError(1, 'unittest')
cce = aiohttp.client_exceptions.ClientConnectorError(connection_key, ose)
cce_pickled = pickle.dumps(cce)
pickle.loads(cce_pickled)
```

Result:

```
Traceback (most recent call last):
  File "/opt/.pycharm_helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/opt/.pycharm_helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/.pycharm_helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/project_neural_mouse/src/ARCHIVE/scratch/scratch_13.py", line 11, in <module>
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_exceptions.py", line 133, in __init__
    super().__init__(os_error.errno, os_error.strerror)
AttributeError: 'str' object has no attribute 'errno'
```

## Your environment

Python 3.6.8, aiohttp.__version__ == 3.6.0

## Additional detail

This issue is posted on StackOverflow here: 

https://stackoverflow.com/questions/58019939/attributeerror-str-object-has-no-attribute-errno?noredirect=1#comment102443264_58019939

I placed a ClientConnectionError exception in a multiprocessing.Queue that was generated by asyncio. I did this to pass an exception generated in asyncio land back to a client in another thread/process.

This exception appears to occurred during the deserialization process reading the exception out of the queue. It looks pretty much impossible to reach otherwise.

```
Traceback (most recent call last):
  File "model_neural_simplified.py", line 318, in <module>
    main(**arg_parser())
  File "model_neural_simplified.py", line 314, in main
    globals()[command](**kwargs)
  File "model_neural_simplified.py", line 304, in predict
    next_neural_data, next_sample = reader.get_next_result()
  File "/project_neural_mouse/src/asyncs3/s3reader.py", line 174, in get_next_result
    result = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "model_neural_simplified.py", line 245, in read_sample
    f_bytes = s3f.read(read_size)
  File "/project_neural_mouse/src/asyncs3/s3reader.py", line 374, in read
    size, b = self._issue_request(S3Reader.READ, (self.url, size, self.position))
  File "/project_neural_mouse/src/asyncs3/s3reader.py", line 389, in _issue_request
    response = self.communication_channels[uuid].get()
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_exceptions.py", line 133, in __init__
    super().__init__(os_error.errno, os_error.strerror)
AttributeError: 'str' object has no attribute 'errno'
```

The minimally reproducible example posted above generates a similar error as the one shown here that I experienced in practice.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Exceptions in `client_exceptions.py`, `http_exceptions.py`, `web_exceptions.py` and `http_websocket.py` are now pickleable. They now can be passed to other processes in multiprocessing.

Also changed the repr of some exceptions. They no longer have the form of incorrect call `typename(somestring)`, but have a form `typename(correct_pos_and_kw_args)` or `<typename some string or attributes>`.

Closes #4077.

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
Ah, I tested on 3.7 and this was one of subtle differences between 3.6 and 3.7.

**Comment by webknjaz** [comment]
@serhiy-storchaka plz add yourself to https://github.com/aio-libs/aiohttp/blob/master/CONTRIBUTORS.txt next time you submit a PR :)

**Comment by serhiy-storchaka** [comment]
Sure! It is not my last PR for aiohttp. :)

**Comment by asvetlov** [comment]
I hope so.
@serhiy-storchaka if you want to get commit rights -- please just let me know.
Your contribution to CPython is the best testimonial that I can imagine.

**Pull request merged**
