### PR TITLE
Fix typo from `pyenv` to `pyvenv`

### PR DESCRIPTION
**Pull request by delirious-lettuce**
## What do these changes do?

Fix a typo, [`pyenv`](https://github.com/pyenv/pyenv) is different from [`pyvenv`](https://docs.python.org/3/library/venv.html?highlight=pyvenv)

## Related issue number

N/A, trivial update

### CODE REVIEW

**Comment by webknjaz** [comment]
@delirious-lettuce plz add it to dictionary, so that sphinx's spellcheck won't complain

**Comment by delirious-lettuce** [comment]
@webknjaz ,

My mistake, I'll add it right away. Just to double check, you mean add it to `aiohttp/docs/spelling_wordlist.txt` ?

**Comment by webknjaz** [comment]
Yes please

**Comment by asvetlov** [comment]
Is the info about Ubuntu bug in pyvenv still relevant?

**Comment by asvetlov** [comment]
Fixed in master.
Thanks for pointing on the problem

**Comment by delirious-lettuce** [comment]
@asvetlov ,

No problem, thanks for your time!

**Pull request closed without merging**
