### PR TITLE
Update contributing guide so new contributors can successfully install dependencies

### LINKED ISSUE #4160: Error while installing dependency using the contributing guide
## Long story short

I cloned the repo and follow the contributing guide [here](https://docs.aiohttp.org/en/stable/contributing.html) then run into a dependency installation error.

## Expected behaviour

By following the guide I should be able to start development.

## Actual behaviour

During the `$ pip install -r requirements/dev.txt` step I got this error
```
    clang: error: no such file or directory: 'aiohttp/_websocket.c'
    clang: error: no input files
    error: command 'clang' failed with exit status 1
    ----------------------------------------
```

After taking a look into `Makefile` I just found out that if I skip the dependency installation step and run `make test` it will correctly install everything for me. I'm going to create a PR to update the document.

## Steps to reproduce

Just freshly clone the repo then follow the contributing guide step by step

## Your environment

aiohttp version: master
OS: macos 10.14.6
python version: 3.7.4

### PR DESCRIPTION
**Pull request by icmpecho**
## What do these changes do?

Update contributing guide so new contributors can successfully install dependencies

## Are there changes in behavior for the user?

no

## Related issue number

Fixes #4160

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by asvetlov** [comment]
Another option can be adding `make develop` command and documenting it.
It can be an alias for `.develop` but without a confusing dot at the front.

**Comment by icmpecho** [comment]
@asvetlov ok I'll fix that. how about something like `make install-dev`

**Comment by asvetlov** [comment]
> how about something like `make install-dev`

Sounds good

**Comment by asvetlov** [comment]
Thanks!

**Pull request merged**
