### PR TITLE
BaseException -> Exception

### PR DESCRIPTION
**Pull request by kvirt**
## What do these changes do?

Fix swallow `BaseException` (`KeyboardInterrupt`)

## Related issue number

https://github.com/aio-libs/aiohttp/issues/2444

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by fafhrd91** [comment]
This change will leak resources

**Comment by asvetlov** [comment]
@fafhrd91 do you suggest catching `BaseException`?

**Comment by fafhrd91** [comment]
For sure If we need to release resourse. We still can re-raise

**Comment by arthurdarcet** [comment]
For the two except in `client.py`, I agree with @fafhrd91, they should definitely stay `BaseException`. They are immediately re-raised so this PR would change any behaviour except that the transport wouldn't be properly closed when a BaseException is raised. This is exactly why #2441 was needed.

For the other two excepts, I think the `set_exception` call should be replaced with a `raise` if the exception is a BaseException (and not an Exception). But I'm having a hard time imagining use cases where the current code would lead to issues.
I guess there might be some edge cases where a BaseException would be swallowed into a future, and never really raised, so raising it immediately is safer.

**Comment by asvetlov** [comment]
Fixed in master

**Pull request closed without merging**
