### PR TITLE
configure raise_for_status per request feature

### PR DESCRIPTION
**Pull request by sky-code**
## What do these changes do?

Add an ability to specify `raise_for_status` parameter per request

## Are there changes in behavior for the user?

This changes has full backward compatibility

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by asvetlov** [comment]
The change has a price: additional API parameter that should be documented and remembered.
Client API already has too long list of available parameters, we should be careful with providing a new one.

On another hand the change doesn't bring a new functionality or saves lines of code. The following snippets are equal:
```
async with client.get(url, raise_for_status=True) as resp:
    await resp.text()
...
async with client.get(url) as resp:
    resp.raise_for_status()
    await resp.text()
```

I need a serious reason to approve the Pull Request.

**Comment by sky-code** [comment]
Main reason for this new parameter is to override value provided to `ClientSession`

For example, you have `ApiClient` class with configured `ClientSession` object property, and you use this client session in `ApiClient` methods, for 10 methods it's ok to have `raise_for_status=True` but for another 3 methods you need `raise_for_status=False`, with current api this is impossible.
If you set `raise_for_status=True` - you set it for **all request** without ability to disable it for any request, so this feature not usable if you need it for **most of cases** but not for **all cases**.

I want to enable `raise_for_status` by default and override it when I need to check response code beyond 200, so this is inverted pattern from checking `resp.raise_for_status()` manually every time to setting `raise_for_status=False` when I expect non 200 response.

```
async with client.get(url) as resp:
    assert resp.status == 404 # if raise_for_status=True you won't be able to get here
    # so you end up with not use raise_for_status in ClientSession

async with client.get(url, raise_for_status=False) as resp:
    assert resp.status == 404 # now now you can reach here
```

**Comment by asvetlov** [comment]
Well, this is another story.
Documentation should be updated, your use case should be mentioned.

**Comment by sky-code** [comment]
I have added documentation

**Comment by asvetlov** [comment]
Thanks

**Pull request merged**
