### PR TITLE
Forbid synchronous context managers

### LINKED ISSUE #2540: Drop await aiohttp.request(...)
Closing request/session is too error-prone in the case, especially if an exception was generated.

The only robust solution is prohibiting `await request()` syntax but supporting `async with request() as resp:` only.

After implementing proposed restriction we'll get very clean context and behavior.

### PR DESCRIPTION
**Pull request by asvetlov**
for ClientSession and test client/server.

Fixes #2540

### CODE REVIEW

**Comment by pfreixes** [comment]
LGTM

**Comment by asvetlov** [comment]
Implementation note: I use `raise RuntimeError` instead of just removing `__enter__` methods for better exception text.
Figured out that `TypeError` is even better exception type.

**Comment by asvetlov** [comment]
@pfreixes please next time approve by github UI, not onlt by `LGTM` comment.
Sure, I have administrator privilege for skipping the check but very appreciate the following formal procedure.

**Comment by pfreixes** [comment]
Oki doki, one question can I click merge button but taking into account that must pass the CI pipeline to finally do it? Something like "Merge if CI passes"

**Comment by asvetlov** [comment]
IMHO Merge button becomes enabled only if CI passed.
There is no "delayed merge".

**Pull request merged**
