### PR TITLE
Move coverage config to setup.cfg

### PR DESCRIPTION
**Pull request by alefteris**
## What do these changes do?

Coverage can also be configured in setup.cfg, so I moved the config there and deleted the`.coveragerc` file. One file less in the project root dir 😄 

## Are there changes in behavior for the user?

No.

## Related issue number

None.

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new entry to `CHANGES.rst`
  * Choose any open position to avoid merge conflicts with other PRs.
  * Add a link to the issue you are fixing (if any) using `#issue_number` format at the end of changelog message. Use Pull Request number if there are no issues for PR or PR covers the issue only partially.

### CODE REVIEW

**Comment by AraHaan** [comment]
Looks like something in the tests have gone wrong.

**Comment by AraHaan** [comment]
Opened #1859 that should fix the failing test. @asvetlov @fafhrd91 I think this PR and mine are not to bad to merge.

**Comment by kxepal** [comment]
You can rebase your PR to have it green to merge.

**Comment by AraHaan** [comment]
@alefteris you should be able to rebase this or now to make this mergeable and for the CI's to now pass.

**Comment by alefteris** [comment]
Thanks a lot for helping out. I rebased and now all checks have passed.

**Comment by kxepal** [comment]
Thanks!

**Pull request merged**
