### PR TITLE
Handle %2f in URL correctly for HttpRequest

### PR DESCRIPTION
**Pull request by ludovic-gasc**
Hi,

I've a problem with HttpRequest to handle %2f in URL (ex: /get/test%2fcase), because HttpRequest will make the request to /get/test/case instead of /get/test%2fcase.

I need this to retrieve data from CouchDB in a database that it has / character in his name.

About my solution, I've used Requests because I know a little bit internally, but I've also find this:
https://github.com/quantmind/pulsar/blob/master/pulsar/utils/httpurl.py

It's only a suggestion to reuse some work from another library, you could also reimplement this piece of code.

Regards.

### CODE REVIEW

**Comment by Lothiraldan** [comment]
It's weird, I think I just hit the same problem but on the server side.

I've two routes:
- /{collection}/{resource_id}
- /{collection}/{resource_id}/{custom_action}

And when I try to get a resource_id containing a /, the server match the second route. @GMLudo You fixed the problem only on client side, right?

**Comment by asvetlov** [comment]
@Lothiraldan you should use three routes:
- /{collection}/{resource_id}
- /{collection}/{resource_id}/
- /{collection}/{resource_id}/{custom_action}

**Comment by asvetlov** [comment]
@GMLudo did you try https://github.com/aio-libs/aiocouchdb ?

**Comment by Lothiraldan** [comment]
@asvetlov Doesn't seems to work, should I open a new ticket for the problem?

**Comment by asvetlov** [comment]
@Lothiraldan 
It works in my example, if I understand you clean.

```
import asyncio
from aiohttp.web import Application, Response


@asyncio.coroutine
def resource(request):
    return Response(
        text='/{collection}/{resource_id}'.format_map(
            request.match_info))


@asyncio.coroutine
def custom_aсtion(request):
    return Response(
        text='/{collection}/{resource_id}/{custom_action}'.format_map(
            request.match_info))


@asyncio.coroutine
def init(loop):
    app = Application(loop=loop)
    app.router.add_route('GET', '/{collection}/{resource_id}', resource)
    app.router.add_route('GET', '/{collection}/{resource_id}/', resource)
    app.router.add_route('GET', '/{collection}/{resource_id}/{custom_action}',
                         custom_aсtion)

    handler = app.make_handler()
    srv = yield from loop.create_server(handler, '127.0.0.1', 8080)
    print("Server started at http://127.0.0.1:8080")
    return srv, handler

loop = asyncio.get_event_loop()
srv, handler = loop.run_until_complete(init(loop))
try:
    loop.run_forever()
except KeyboardInterrupt:
    loop.run_until_complete(handler.finish_connections())
```

**Comment by Lothiraldan** [comment]
With this example it's more visible: https://gist.github.com/Lothiraldan/2e4b36ac55946ff0ba3b

When I call ~http://localhost:8080/collection/resource%2Fbb~, I get this response:

```
<MatchInfo {'collection': 'collection', 'resource_id': 'resource', 'custom_action': 'bb'}: <DynamicRoute [GET] /{collection}/{resource_id}/{custom_action} -> <function custom_aсtion at 0x10bd6cea0>>
```

And I would like this response:

```
<MatchInfo {'resource_id': 'resource/bb', 'collection': 'collection'}: <DynamicRoute [GET] /{collection}/{resource_id} -> <function resource at 0x107070730>>
```

I think it's not possible right now because we unquote the path before doing the route matching, do you see a way I could make it working or should I my API differently?

**Comment by asvetlov** [comment]
Aha, got it.

The problem is inside `Reqiest.path` property: it unquotes the path (https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/web_reqrep.py#L172).

I suggest adding `unquoted_path` property for using in `UrlDispatcher`, `path` should be `reify` property for `unquoted_path`.

@Lothiraldan would you make a Pull Request? Some tests for new functionality are required.

**Comment by ludovic-gasc** [comment]
Hi guys,

Sorry by my delayed response, I'm actually very busy with projects.

@Lothiraldan: Yes, from the client side.
@asvetlov: Yes, you have this library on our production. However, in the future, we shouldn't use anymore, because we're replacing our CouchDB instances by PostgreSQL+JSONB: More efficient, but the main advantage is JSONB SQL syntax to search data with SQL queries, you have no equivalent in CouchDB, the views aren't enough.

**Comment by kxepal** [comment]
Offtopic.
@GMLudo On behalf of CouchDB PMC, may I ask you to provide your feedback to us on the [mailing list](user-subscribe@couchdb.apache.org), why do you want to migrate to PostgreSQL and why you'd found JSONB SQL syntax better than views? This should be interesting and helpful (: Sure, when you'll have a time for this...

**Comment by Lothiraldan** [comment]
@asvetlov I could and will make a PR!

**Comment by ludovic-gasc** [comment]
@kxepal: No time right now to give you the complete dump, I've a D-day tomorrow with a very big client, several daemons with AsyncIO+aiohttp.web+API-Hour+Panoramisk, I hope I'll have the authorization to publish the benchmarks, it's an interesting use case ;-)

About CouchDB and PostgreSQL JSONB, we started to have big issues for the billing: We have a lot clients, hierarchization problems with commissions between levels.
With JSONB, it's enough efficient to calculate data on realtime, without cache.

I'll give you several concrete examples where we had issues.
To understand the complexity of our business rules calculations, the smallest SQL query in this aiohttp.web application is 10 lines. The biggest is around 45 lines.
It isn't an intellectual masturbation of engineers, it's because we try to have an attractive business model for our partners.

**Pull request closed without merging**
