### PR TITLE
doc: send, send_json... are regular methods.

### PR DESCRIPTION
**Pull request by greut**
## What do these changes do?

Fix the documentation of `aiohttp.ClientWebSocketResponse`

http://aiohttp.readthedocs.io/en/stable/client_reference.html#aiohttp.ClientWebSocketResponse.send_str

## Are there changes in behavior for the user?

Nope.

## Related issue number

Dunno

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new entry to `CHANGES.rst`
  * Choose any open position to avoid merge conflicts with other PRs.
  * Add a link to the issue you are fixing (if any) using `#issue_number` format at the end of changelog message. Use Pull Request number if there are no issues for PR or PR covers the issue only partially.

### CODE REVIEW

**Comment by fafhrd91** [comment]
eventually those methods will become coroutines. I specifically marked them as comethods during transition period

**Comment by greut** [comment]
@fafhrd91 shouldn't they behave like so then?

**Comment by fafhrd91** [comment]
Those methods return coroutine objects. We use similar approach in number is places

**Comment by greut** [comment]
@fafhrd91 my bad, no warnings no more. I probably missed an update. Sorry for your time and thanks!

**Comment by fafhrd91** [comment]
sure, mp

**Pull request closed without merging**
