### PR TITLE
Add type hinting

### PR DESCRIPTION
**Pull request by mosquito**
## Checklist

- [X] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by mosquito** [comment]
For me it's a little bit painful when I don't see `web.Application.router`s methods,  or don't see client response attributes and methods.

This changes already tested by me on my PyCharm (with `pip install -e ../aiohttp`).

**Comment by asvetlov** [comment]
No. Tools are not ready yet, adding type hints without checks is pointless and can make a harm easy.
See #1749

**Comment by asvetlov** [comment]
Say, your PR declares a return type for `client.request` as a coroutine with `ClientResponse` return type but actually it is a much more complex object with async context manager interface.

**Comment by mosquito** [comment]
@asvetlov this "complex object" inherited from coroutine. 

Note about tooling: PyCharm and SublimeText (with anaconda) supports this. This fixes needs only for "developer experience".

It's sad that I have to write every time `# type: ClientResponse`:

```python

...
        async with self.client_session(headers=headers) as session:
            async with session.get(url) as response:  # type: ClientResponse
                result = await response.json()
...
```

**Comment by asvetlov** [comment]
1. Type for async context manager with `__await__` method should be different from mypy/types perspective.
2. You are talking about "developer experience", I am about type correctness checking. If we will add types we should add type checker to our test suite. Unchecked type declaration is ad bad as code not covered by tests from my perspective.

So we need a robust tool. Mypy doesn't support https://www.python.org/dev/peps/pep-0561/ yet unfortunately, thus it cannot be used *right now*. I hope mypy dev team will fix it. Personally I have no time for working on mypy unfortunately.

**Comment by mosquito** [comment]
Should we make `.pyi` file with type declaration?

**Comment by asvetlov** [comment]
We should have working checker with PEP 0561 implemented first.
After that we can start a discussion about typing strategy.
I suspect we will have a mix of stub files for C extensions at least and embedded annotations.

**Pull request closed without merging**
