### PR TITLE
Awaitable _CoroGuard and fix `ClientSession.close` warning message

### PR DESCRIPTION
**Pull request by litwisha**
## What do these changes do?

1) [_CoroGuard.](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/helpers.py#L65) is awaitable.  
2) Fix warning [message](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L538) for `ClientSession.close()` method. (from `ClientSession.close() is not coroutine` to `ClientSession.close() is coroutine`)

## Related issue number

#2026 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.

### CODE REVIEW

**Comment by asvetlov** [comment]
Warning text should be fixed.
The guard encourages `await session.close()` usage while we should support just `session.close()` for a while for sake of backward compatibility.

**Comment by asvetlov** [comment]
Please update warning message as well

**Comment by asvetlov** [comment]
Also please add a record in `./changes` folder

**Comment by litwisha** [comment]
@asvetlov I have completed all the notes. It seems to be ready for merge

**Comment by asvetlov** [comment]
Thank you.
I'll process the PR a bit later.

**Comment by asvetlov** [comment]
Thanks!

**Pull request merged**
