### PR TITLE
WIP: Add type hints everywhere

### PR DESCRIPTION
**Pull request by asvetlov**
Enable strong mypy checks to make sure that types are correct.

### CODE REVIEW

**Comment by kornicameister** [comment]
@asvetlov happy to help. I am quite interested in getting this in since I am using both mypy and aiohttp in my project ;-). Those little errors in Neovim aren't necessary helping :D.

I will check out your PR and see if there's anything more to work on.
Or maybe I will find sth else ;-)

**Comment by kornicameister** [comment]
@asvetlov If you want, might be that #3289 is something you might want to pull in as well. I am not sure how the customs are here, but I usually prefer latest available libraries ;-).

**Comment by asvetlov** [comment]
@kornicameister if you want to help we can do the following:
1. I'll disable strict mypy mode (comment strict options in config) and merge the PR
2. You can pick up the master branch, uncomment these settings and work on some file
3. Your PR(s) will fail on CI, I'll check it manually and merge.

Adding types to all files is a big work, I appreciate any help

**Comment by kornicameister** [comment]
Yeah...why not 🤔. I will try to get sth as soon as I have some time off being dad 😃.

That said I will wait for you to merge this one. I suppose I can actually pick up this branch as a starting point for the being.

**Comment by kornicameister** [comment]
@asvetlov FYI: starting with `aiohttp/payload.py`

**Comment by asvetlov** [comment]
@kornicameister cool!
I'm about to make the PR green

**Pull request merged**
