### PR TITLE
Simplify HTTP pipelining implementation

### PR DESCRIPTION
**Pull request by pfreixes**
## What do these changes do?

HTTP pipelining is still supported but implemented
as a simple FIFO queue with just 1 Asyncio task attending
it. It might allow optimizing infrastructures based on microservices
that do not use HTTP pipelining.

## Are there changes in behavior for the user?

No

## Related issue number

#2109

### CODE REVIEW

**Comment by pfreixes** [comment]
@fafhrd91 my idea was working on getting rid of some of the layers in a separated PR once it gets merged, just for simplicity and make easier the reviewing process. But, if you agree I can try to do it in the same PR.

/cc @asvetlov

**Comment by fafhrd91** [comment]
it is up to you, I'd remove StreamWriter at the same time

**Comment by asvetlov** [comment]
I prefer two steps: the PR is huge already.

**Comment by asvetlov** [comment]
Thanks, @pfreixes

**Pull request merged**
