### PR TITLE
Improve typings in multipart

### PR DESCRIPTION
**Pull request by kornicameister**
Adjusts typings to match the documentation.

No, those were just typings improvements.
I've changed the code in one place but those changes were limited to:
- using (IMHO) more appropriate looping technique
- accounting for changed typins

#3621

No

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by kornicameister** [comment]
About non changing the user behavior. There's one place that I am not particularly sure of. It is the place around `assert field_content_type is not None`. I suppose that's having something with the typing. Unfortunately the FileField expects is set, so I though that if anything goes wrong there and content_type is actually `None` is is best to throw the processing out.

**Comment by kornicameister** [comment]
@asvetlov is this still needed by any means?

**Comment by asvetlov** [comment]
1. The PR doesn't pass CI tests. I don't review such PRs usually.
2. Please keep `while` loop in `web_request.py`. I agree that `async for` would be better but the change introduces a big hard-to-review diff without strong reason.

**Comment by kornicameister** [comment]
Ok, @asvetlov that sounds like a plan. I will close this PR and first resolve the typings issue and then make a PR with `async for` given that it is doable to these changes in separation. I don't remember what was the deal with adding `async for`, but for sure I have done that for some reason.

Anyway, I will try to deal with typings first.

PS. sorry for not dealing with CI first.

**Comment by kornicameister** [comment]
Closing now

**Pull request closed without merging**
