### PR TITLE
fix async with in TestClient.ws_connect

### PR DESCRIPTION
**Pull request by barrachri**
## What do these changes do?
Add async with support for TestClient.ws_connect

## Are there changes in behavior for the user?
No

## Related issue number
#2525 

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Issue numbers in titles don't work as links and generally don't mean much to people. 

Best to use a short descriptive title and add the issue number to the body.

**Comment by barrachri** [comment]
Thanks, should be more expressive now.

**Comment by asvetlov** [comment]
The change looks good but worth for a new test for added functionality.
`tests/test_test_utils.py` already has a test for `await TestClient.ws_connect()`, adding a new one for `async with TestClient.ws_connect()` should be easy.

**Comment by asvetlov** [comment]
thanks!

**Pull request merged**
