### PR TITLE
PEP fixes

### PR DESCRIPTION
**Pull request by thehesiod**
- don't use private attributes
- mark where abstract methods need to be implemented
- don't use shadow var name from global scope
- use snake case

### CODE REVIEW

**Comment by thehesiod** [comment]
@asvetlov looks like there's a test framework issue:
`TypeError: unhashable type: 'HTTPMethodNotAllowed'`

**Comment by asvetlov** [comment]
Yes, it is the regrssion: #2579

**Comment by asvetlov** [comment]
Sorry, accidental closing

**Comment by asvetlov** [comment]
Something is still wrong.
@thehesiod could you take a look?

**Comment by asvetlov** [comment]
Thanks!

**Comment by thehesiod** [comment]
TY!

**Pull request merged**
