### PR TITLE
use f-strings

### PR DESCRIPTION
**Pull request by ikamensh**
## What do these changes do?

Convert legacy formatting to f-strings.

## Are there changes in behavior for the user?

No change

## Summary
This change is derived by running a tool, `flynt`. As there's already pyupgrade in pre-commit, the significant difference is e.g. converting multi-line expressions. 

```
Files modified:                            40
Character count reduction:                 1483 (0.09%)

Per expression type:
Old style (`%`) expressions attempted:     56/67 (83.6%)
`.format(...)` calls attempted:            84/98 (85.7%)
No concatenations attempted.
F-string expressions created:              103
```

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] too minor to add myself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder -- is refactoring  worth mentioning here?
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by ikamensh** [comment]
Will open this PR once it passes CI - let me know if it's overall a good idea though to do bulk transform

**Comment by asvetlov** [comment]
I believe the master and 3.8 branch have such transformation already -- thanks to pyupgrade

**Comment by ikamensh** [comment]
these were done on top of master, so those 103 transformations are the cases that pyupgrade can't handle.

**Comment by asvetlov** [comment]
Ok with the idea but not care too much. I did not carefully review every affected line yet

**Pull request closed without merging**
