### PR TITLE
Added typing to examples

### PR DESCRIPTION
**Pull request by WisdomPill**
I forgot to create a pull request for this, I do not know if it is welcome or useful by any means.
I fell that people would start using types more often, it saves us from some difficult to find bugs, so why not show it.

## What do these changes do?

Add type hints to examples so that it is easier to get up and going with typed code

## Are there changes in behavior for the user?

Not really

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by WisdomPill** [comment]
I do not know what kind of change I should add in `CHANGES`, @asvetlov do you have any suggestions?

**Comment by asvetlov** [comment]
I think we don't need a CHANGES file for this PR but the linter check should be green.
This is the pre-requirement for merging.

**Comment by WisdomPill** [comment]
I am on it, a new commit is coming

**Comment by asvetlov** [comment]
Thanks!

**Pull request merged**
