### PR TITLE
App handle split

### PR DESCRIPTION
**Pull request by NewVadim**
## What do these changes do?

Split Application._handler() by functions.
Fix of list middleware in assert response is instance StreamResponse.

## Are there changes in behavior for the user?

The user can override the behavior a application handler in your own applications.
For example override only middleware.

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by asvetlov** [comment]
I see no strong motivation.
The API is *internal*, user should never override it by custom code -- neither all together nor partially.

**Comment by NewVadim** [comment]
I override all `_handler` to add their own processing middlewares.
Also the logical division of functions will not be superfluous.

Skip middleware example:
```python
async def wrap_middlewares(self, match_info):
    handler = match_info.handler
    skip_middlewares = getattr(handler, '__skip_middlewares__', set())

    for app in match_info.apps:
        for m, new_style in app._middlewares:
            full_path = '{}.{}'.format(m.__module__, m.__name__)
            if '__all__' in skip_middlewares:
                break
            elif full_path in skip_middlewares:
                continue

            if new_style:
                handler = partial(m, handler=handler)
            else:
                handler = await m(app, handler)

    return handler
```
P.S.: I don't insist.

**Comment by asvetlov** [comment]
In my mind skipping not needed middlewares should be done in the following way:
1. Create main app
2. Push every lightweight handler not required by complex middleware stack into one sub application.
3. Put others into another app with corresponding middlewares.

Thus in theory lightweight handlers should be avoided by middlewares from bullet 3.
Maybe it is not true: there is #2454 issue.
I pretty sure I had tests for the case but maybe the behavior is broken.
I didn't test the issue yet -- if we have a broken functionality the situation should be fixed. Could you check?

P.S.
From my perspective the `Application` class is *final*/*sealed* -- no class should derive from it.
If users still inherit from `Application` -- it is a sign of every the concept misunderstanding or lack in aiohttp.web functionality. Let's fix it!

P.P.S.
*Freezing* classes from inheritance is a very good idea, it keeps a place for further modifications of the library. Otherwise we'll get always blocked by some potential backward incompatibilities.
The library is used in the wild, making every implementation detail a part of public API simply stops every improvement: maybe it breaks some code. That's why public API exists.

**Comment by NewVadim** [comment]
A sub application is not working and it is not very convenient.

```python


from aiohttp import web

async def index(request):
    print('*'*8, request.path, '*'*8)
    print('Index!')
    return web.Response(body=b'Index', content_type='text/plain')


async def login(request):
    print('*' * 8, request.path, '*' * 8)
    print('Login!')
    return web.Response(body=b'Login', content_type='text/plain')

async def cabinet(request):
    print('*' * 8, request.path, '*' * 8)
    print('Cabinet!')
    return web.Response(body=b'Cabinet', content_type='text/plain')


@web.middleware
async def auth_middleware(request, handler):
    print('m' * 8, request.path, 'm' * 8)
    print('Auth middleware!')
    return await handler(request)


root_app = web.Application()
admin_app = web.Application(
    middlewares=[auth_middleware],
)
admin_login_app = web.Application()

root_app.router.add_get('/', index, name='index')
admin_app.router.add_get('/cabinet/', cabinet, name='admin:cabinet')
admin_login_app.router.add_route('*', '/', login, name='login')

admin_app.add_subapp('/login', admin_login_app)
root_app.add_subapp('/admin/', admin_app)


web.run_app(root_app)

```

```bash
$ python server.py 
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
******** / ********
Index!
mmmmmmmm /admin/login/ mmmmmmmm
Auth middleware!
******** /admin/login/ ********
Login!
mmmmmmmm /admin/cabinet/ mmmmmmmm
Auth middleware!
******** /admin/cabinet/ ********
Cabinet!
```

**Comment by NewVadim** [comment]
So, i close pull request.

**Pull request closed without merging**
