### PR TITLE
Remove @unittest_run_loop

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
Removes the now unneeded @unittest_run_loop from master.

### CODE REVIEW

**Comment by webknjaz** [comment]
@Dreamsorcerer is the new default on regardless of the Python version?

**Comment by Dreamsorcerer** [comment]
> @Dreamsorcerer is the new default on regardless of the Python version?

Appears to have a fallback on asynctest, so looks like it:
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/test_utils.py#L60

**Comment by webknjaz** [comment]
> Appears to have a fallback on asynctest, so looks like it:
> [https://github.com/aio-libs/aiohttp/blob/master/aiohttp/test_utils.py#L60](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/test_utils.py?rgh-link-date=2021-03-04T14%3A28%3A17Z#L60)

Could you make sure that there's a test for this then?

**Comment by Dreamsorcerer** [comment]
> Could you make sure that there's a test for this then?

Indeed, the test_test_utils.py covers this already:
https://github.com/aio-libs/aiohttp/blob/unittest1/tests/test_test_utils.py#L105-L109

**Review by webknjaz — APPROVED** [review]

**Pull request merged**
