### PR TITLE
Move documentation to docs.aiohttp.org

### PR DESCRIPTION
**Pull request by asvetlov**
http://docs.aiohttp.org/en/stable/ already exists BTW

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Looks good.

What about google webmaster tools and `<link rel="canonical" href="...">` to encourage google to show the right domain?

Or can you do a 301 from http://aiohttp.readthedocs.io? Might be bad for SEO to have "duplicated" content at `docs.aiohttp.org` and `aiohttp.readthedocs.io`?

**Comment by asvetlov** [comment]
Installed google webmaster, waiting for crawler.

**Comment by popravich** [comment]
https?

**Comment by kxepal** [comment]
https://docs.aiohttp.org
```
docs.aiohttp.org uses an invalid security certificate. The certificate is only valid for the following names: *.readthedocs.io, readthedocs.io Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

I don't think that would be simple.

**Comment by asvetlov** [comment]
Unfortunately it doesn't work: rtfd/readthedocs.org#2652

**Comment by samuelcolvin** [comment]
Surely just use cloudflare, it's free and should fix in it with a few seconds work.

(I mean just use their HTTPS proxy in front of readthedocs)

**Comment by samuelcolvin** [comment]
Also on http://docs.aiohttp.org/en/stable/:

```
<link rel="canonical" href="http://aiohttp.readthedocs.io/en/stable/" />
```

Is this because this PR hasn't been released yet?

**Comment by asvetlov** [comment]
@samuelcolvin makes sense, I'll setup it.
Try http://docs.aiohttp.org/en/latest/ for master.
stable is for last tagged release.

**Comment by asvetlov** [comment]
@samuelcolvin cloudflare works like a charm, very thank you: https://docs.aiohttp.org/en/stable/
Just for information: I use cloudflare for both `aiohttp.org` and `aio-libs.org`.

`aio-libs.org` is just a CNAME for `aio-libs.github.io`,  https://github.com/aio-libs/aio-libs.github.io repo.

`aiohttp.org` is hosted on http://netlify.com (thanks again @samuelcolvin) and proxied by cloudflare.
The repo is https://github.com/aio-libs/aiohttp-site
https://docs.aiohttp.org/ is proxied by cloudflare as well.

Looks like Free Plan for both used tools doesn't allow me to add you guys as collaborators -- but I believe we can live with it.

If you need access for git repos for sites -- please ask me.

Future plans are in #2520

**Comment by samuelcolvin** [comment]
Cloudflare's proxy/CDN does not play well with netlify's, and sites are much faster without the cloudflare proxy. I found out the hard way that the best option is to disable cloudflare's proxy. You can still get free automatic ssl, you just have to prompt netlify to generate the ssl cert after disabling cloudflare's proxy.

Doesn't matter much, but I'm pretty sure netlify allows multiple contributors on all tiers.

**Pull request merged**
