### PR TITLE
tests_require: add trustme

### PR DESCRIPTION
**Pull request by dotlambda**
It is required since https://github.com/aio-libs/aiohttp/pull/3487.

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by asvetlov** [comment]
I've missed this.
How do you use `test_require`? Do you run `python setup.py test`?

**Comment by dotlambda** [comment]
> How do you use test_require? Do you run python setup.py test?

I do. And as long as `tests_require` is specified, it should be complete.

Actually, there are more missing: pytest-mock, pytest-cov trustme and brotlipy.

**Comment by webknjaz** [comment]
@dotlambda the thing is that using this mechanism is discouraged, we don't really use it and should probably just remove that completely.

**Comment by asvetlov** [comment]
@webknjaz agree 
We need either use `test_requires` in our Travis CI or drop this facility.
I'm inclining to removal.

**Comment by webknjaz** [comment]
No, we don't use that at all. But we should probably consider it a breaking change for ones who use it so not backport. Maybe a deprecation warning though.

**Comment by dotlambda** [comment]
I don't have a problem with removing it.

**Comment by asvetlov** [comment]
Our CI is broken now.
Please keep the PR open as the reminder.
I'll close the PR after preparing a new one for dropping `python setup.py test` command.

**Comment by asvetlov** [comment]
#3752 drops `setup.py test` support

**Pull request closed without merging**
