### PR TITLE
Fix a middleware example in docs

### PR DESCRIPTION
**Pull request by ahui132**
## What do these changes do?
Fix a middleware example in `docs/web.rst`.

## Are there changes in behavior for the user?
No

## Related issue number
No

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes

### CODE REVIEW

**Comment by samuelcolvin** [comment]
@asvetlov how strict are we on adding to `CHANGES` even for small changes like this?

**Comment by asvetlov** [comment]
I think we don't need CHANGES update for such trivial PRs.
The behavior is not changed, no new features added.

**Comment by samuelcolvin** [comment]
Makes sense. I'll merge when passed.

**Comment by samuelcolvin** [comment]
Thanks!

**Pull request merged**
