### PR TITLE
added _reuse_address and _reuse_port to web_runner.TCPSite.__slots__

### PR DESCRIPTION
**Pull request by jancespivo**
Hi,
`_reuse_address` and `_reuse_port` are not included in `TCPSite.__slots__`

```python
import aiohttp.web
app = aiohttp.web.Application()
aiohttp.web.run_app(app)
```
Invokes:
`AttributeError: 'TCPSite' object has no attribute '_reuse_address'`

Best regards

### CODE REVIEW

**Comment by asvetlov** [comment]
Hmm. This is a bug definitely but I wonder why tests are passed without slots.
Your code snipped didn't raise an error too.

**Comment by drpoggi** [comment]
I believe this error only happens on 3.7 where now `ABC` defines a `__slots__`

**Comment by asvetlov** [comment]
You are right. This explains everything.

**Comment by jancespivo** [comment]
Yes, sorry. It was actually python 3.8.0a0 I forgot change the `venv` :man_facepalming:
I am a little suprised the using of `__slots__`  is useless for class inherited from `ABC` in python < 3.7

**Comment by drpoggi** [comment]
It's not useless, it just requires subclasses to be explicit.

**Pull request merged**
