### PR TITLE
Add GNS3 to powered by

### PR DESCRIPTION
**Pull request by noplay**
This PR add GNS3 to powered by aiohttp.

It's the foundation of the GNS3 server which allow user to emulate network. It's use by students to pass certification  and by network engineer for simulating operations.

Because it's a popular open source project in the world of the network engineers, you can be sure any big organisation has somewhere a GNS3 installation with aiohttp.

And thanks to high quality open source project like aiohttp. We can provide a free tool that enable student around the world to learn networking for almost no money except the certification cost.

So thanks to everyone !

### CODE REVIEW

**Comment by asvetlov** [comment]
Thank you

**Comment by sallyhaj** [comment]
GNS3 doesn't work with aiohttp 2.3.X any more, we have to stick with 2.2.X version of aiohttp, I already report a bug there, and hope you both find a solution.

**Comment by asvetlov** [comment]
Do you have related issue in aiohttp?

**Comment by sallyhaj** [comment]
When I run gns3 with python3-aiohttp-2.3.0, I get this message
`"Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connection refused"`
and
`"pkg_resources.DistributionNotFound: The 'aiohttp<2.3.0,>=2.2.0' distribution was not found and is required by gns3-server"`

**Comment by asvetlov** [comment]
Not too many information about first problem.
The second is most likely by aiohttp version restrictions in `gns3-server` `setup.py`.

**Comment by sallyhaj** [comment]
The both issues can be solve by downgrade python3-aiohttp-2.3.X to python3-aiohttp-2.2.X.
I think gns3 team should upgrade the app.
https://github.com/GNS3/gns3-server/pull/1205/cmmits/a7412d1c879920c3b2c2871763aafbe6836d1ed7

**Comment by julien-duponchelle** [comment]
If you use Ubuntu use the gns3 official gns3 package it's embed a
compatible version of aiohttp independent of the distribution releases
cycle

**Comment by sallyhaj** [comment]
No, I am using Fedora 27 with gns3-server 2.1.0, from the official repositories.
the issue came up after the update of aiohttp to 2.3.X.
By the way ubuntu uses gns3 (0.8.7-2)

**Comment by julien-duponchelle** [comment]
Their is ubuntu package on gns3.net.

**Comment by sallyhaj** [comment]
Oh, you are right.
But they use python3-aiohttp (2.2.3)

**Pull request merged**
