### PR TITLE
Change typing of the secure argument on StreamResponse.set_cookie

### LINKED ISSUE #4204: Contradiction between documentation and annotation of the secure parameter of set_cookie()
The `secure` parameter of `StreamResponse.set_cookie()` is [documented](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.StreamResponse.set_cookie) as `bool`, but is [annotated](https://github.com/aio-libs/aiohttp/blob/62365364889981a2e5d3cd36a25240c9c38693fe/aiohttp/web_response.py#L172) as `Optional[str]`.

What is right?

### PR DESCRIPTION
**Pull request by paulefoe**
## What do these changes do?

This change fixes the contradiction between docs and annotation in code

## Are there changes in behavior for the user?

No

## Related issue number

This commit fixes  #4204

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by paulefoe** [comment]
@asvetlov I think docs are correct already, aren't they? It was only the typings that were wrong.

https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.BaseRequest.secure

**Comment by asvetlov** [comment]
There is also https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.StreamResponse.set_cookie where types for parameters are outdated for `secure` and `httponly`

**Comment by paulefoe** [comment]
I updated `httponly` param. About `secure` everything seems correct tho, or am I missing something?

**Comment by asvetlov** [comment]
Thanks!

**Pull request merged**
