### PR TITLE
Reorganize client documentation

### PR DESCRIPTION
**Pull request by asvetlov**
Split client usage into Quickstart, Advanced Usage and Reference.

### CODE REVIEW

**Comment by asvetlov** [comment]
Our doc pages are too huge, I'm trying to split them.
The main idea is: have a very small set of top level topics, push everything one or two levels deeper.

I understand the PR is too huge for careful reviewing.

The proposal is: I'll do all required reorganization in the PR and merge it.
The doc will be available on https://docs.aiohttp.org/en/latest/
After that I'll ask @aio-libs/aiohttp-committers to look on result and propose improvements.

**Comment by kxepal** [comment]
@asvetlov how about to publish this branch on RTD so we can compare before vs after?

**Comment by asvetlov** [comment]
@kxepal sorry, I not sure if it even possible.
But you can clone the repo and run `make doc`.
My work is pretty done now, I quite happy with the result.
We can do more improvements, sure -- but the first step looks cool for me at least.

**Comment by kxepal** [comment]
Here we go: https://docs.aiohttp.org/en/docs/client.html
UPD: this link won't be active once PR get merged. So hurry up to review @aio-libs/aiohttp-committers team!

**Comment by pfreixes** [comment]
Just a couple of things at first glance.

Lets evolve a bit more the DNS chapter about disabling, cache timeout and so on

Regarding the Connector section says explitly that the instance onwnership is taken by the session, if connector_owner param is properly set  the connector can be shared btw sessions.

**Comment by asvetlov** [comment]
@pfreixes 

> Lets evolve a bit more the DNS chapter about disabling, cache timeout and so on

Maybe it needs an another rst file? Or just a section in `client_advanced.rst`?
Anyway please make an issue.

> Regarding the Connector section says explicitly that the instance onwnership is taken by the session, if connector_owner param is properly set the connector can be shared btw sessions.

Good catch! Please file an issue and make a PR after this task will be merged. It shakes docs structure too much. I afraid any docs change is blocked until the merge -- that's why I would like to to the merge very tomorrow if nobody objects.

**Comment by pfreixes** [comment]
I agree to evolve this documentation with the future PR, therefore LGTM and I will make two new PR to improve the DNS and Connectors section.

**Comment by asvetlov** [comment]
The doc is need a love for more improvements but I've merged the PR to not stop anybody on this way.

**Pull request merged**
