### PR TITLE
Drop user supplied loop

### PR DESCRIPTION
**Pull request by asvetlov**
For sake of #2530

The mode is exists for not closing the loop for sake of later reusage, I believe we can invite more robust way by #2530

### CODE REVIEW

**Comment by kxepal** [comment]
So now we always use asyncio global loop and if I want/need to run an app in different one, I should run it in different thread?

**Comment by asvetlov** [comment]
Running two loops in parallel in the same thread is impossible, isn't it?
The program should run one loop per thread (except unittest case), most likely the single loop in main thread per process.

**Comment by donkahuna** [comment]
If I want to change the loop, for example use uvloop ? How can I do this ?

**Comment by asvetlov** [comment]
https://docs.python.org/3/library/asyncio-eventloops.html#asyncio.set_event_loop_policy

**Pull request merged**
