### PR TITLE
Site and AppRunner

### LINKED ISSUE #2121: Split async server running functions
## Long story short

The requirement to have `run_app` as only execution of the server is not enough for some applications. It would be nice if this run_app functionality could be divided in two functions, `start()` and `cleanup()`, as many other libraries do. After all aiohttp is not the core of my app.

The idea is I want to be in charge of the main loop and control how and when it runs.

## Expected behaviour

Not to modify existing applications when including aiohttp.

## Actual behaviour

`aiohttp` get's to be the centre of the application by running `run_forever()` inside the only provided function to run the web server part.

## Steps to reproduce

1. Write `asyncio` application
2. Try to include web interface using aiohttp
3. Modify application to be run with aiohttp as the centre of it, synchronously.

### PR DESCRIPTION
**Pull request by asvetlov**
I'm trying to cleanup infrastructure for web application runners.

The PR introduces a `site` and `AppRunner` concepts.

Fixes #2121 and #2375 
Supersedes #2465

The work is still not finished yet but I believe my intention is clear.

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Can you give an example of how this would work and how it's better than the current situation?

**Comment by asvetlov** [comment]
`run_app` functionality could be implemented like
```
runner = AppRunner(app)
await runner.initialize()  # setup app loop and run `on_startup()` signal.
site = HTTPSite(runner, 'localhost', 8000)
await site.start()
sslsite = HTTPSite(runner, 'localhost', 8443, ssl_context=....)
await sslsite.start()
# wait for closing
await runner.finalize()  # close sites, call app.cleanup()
```

**Comment by asvetlov** [comment]
`web.run_app()` is fully reimplemented on top of `AppRunner` and sites.
Working on 100% test coverage and docs.

**Comment by asvetlov** [comment]
I'm going to merge the PR.

Documentation is needed but I'll do it in separate PR.
Implementation affects many files, better to merge it quickly to avoid permanent code divergency and  merge conflicts,

**Pull request merged**
