### PR TITLE
Fix test event loop

### PR DESCRIPTION
**Pull request by cecton**
## What do these changes do?

Set the current event loop properly during the test.

## Are there changes in behavior for the user?

Some functions that use the default event loop will now work properly: asyncio.create_subprocess_exec and asyncio.create_subprocess_shell

## Related issue number

#2058 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `changes` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by asvetlov** [comment]
No. We intentionally disabled default event loop to check for passing the loop explicitly everywhere in aiohttp.
This behavior should be kept at least while we support Python < 3.5.3.

But your problem has another solution: just call `loop.get_child_watcher()` after a new loop creation.

**Comment by cecton** [comment]
@asvetlov ah thanks! Makes totally sense.

Then would it be a good idea to add this call in the setup_test_loop? Because apparently I'm not the only one to have failed to understand.

**Comment by cecton** [comment]
Actually that won't work. `get_child_watcher` is a method of a policy, not a loop...

**Comment by asvetlov** [comment]
Ooops, I see.
But should be a way for attaching a new loop without making it default.

**Comment by cecton** [comment]
I found a way ^_^

**Comment by cecton** [comment]
Actually I'm not entirely sure that you want to enforce the developers to give the event loop explicitly. According to my memory of the doc of asyncio, this is highly "recommended". But enforcing it will only break all the applications that rely on that behavior. For once, I'm the one who suggest to be flexible on that.

**Comment by cecton** [comment]
I close this PR and re-open it for master because it will now be a feature and not a fix.

**Pull request closed without merging**
