### PR TITLE
Update docs with mention to use of lists in params

### PR DESCRIPTION
**Pull request by Lonami**
## What do these changes do?

These changes address https://github.com/aio-libs/aiohttp/issues/4714#issuecomment-626668791.

## Are there changes in behavior for the user?

No, this is just a documentation change.

## Related issue number

#4714 

## Checklist

- [ ] ~~I think the code is well written~~ (there is no code)
- [x] Unit tests for the changes exist (as long as docs are tested)
- [x] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by Lonami** [comment]
Some notes:

* I'm not sure if `yarl 1.4.3` will be the version that has these changes, but that can be easily be changed.
* I considered updating the `:param params:` of https://raw.githubusercontent.com/aio-libs/aiohttp/master/docs/client_reference.rst to include a mention of this, however that place doesn't even document only `str` and `int` are allowed so I decided against it.

**Comment by asvetlov** [comment]
1. The proper yarl version is 1.5
2. I'm not very happy with the wording. I believe that MultiDict usage should be recommended in the first place, with fallback to nested lists. Maybe f90f803c is not ideal; please feel free to improve the text

**Comment by Lonami** [comment]
> The proper yarl version is 1.5

Yeah, after several months I don't expect my guess to be accurate, that's why I requested a review early with my concerns 😉

> I believe that MultiDict usage should be recommended in the first place, with fallback to nested lists. 

Well, in that case the example could be put first and then the one where lists are used. Though this is all comes down to opinion and since you're a maintainer you have the final say on this, not me.

> Maybe f90f803c is not ideal; please feel free to improve the text

I can't find that commit (https://github.com/aio-libs/aiohttp/commit/f90f803c is a 404), could you provide a link?

**Comment by asvetlov** [comment]
Ooh, sorry. The actual commit number is 766897cb.
I've finally found a time for the library housekeeping, will release a new version soon after cleaning up the list of pending pull requests.

**Pull request closed without merging**
