### PR TITLE
Async write headers

### PR DESCRIPTION
**Pull request by asvetlov**
Make `writer.write_headers()` a coroutine

### CODE REVIEW

**Comment by kxepal** [comment]
LGFM, but could you remind me, please, why all this need? What's the goal?

**Comment by webknjaz** [comment]
I guess it's related to https://github.com/aio-libs/aiohttp/pull/2743#issuecomment-368309217, right?

**Comment by asvetlov** [comment]
No, it is for #2698

**Comment by asvetlov** [comment]
After switching all writes to coroutines we can drop write buffers.

**Comment by kxepal** [comment]
Cool! Thanks.

**Pull request merged**
