### PR TITLE
Backport llhttp to 3.8

### PR DESCRIPTION
**Pull request by asvetlov**
null

-----
[View rendered .github/ISSUE_TEMPLATE.md](https://github.com/aio-libs/aiohttp/blob/llhttp-3.8/.github/ISSUE_TEMPLATE.md)
[View rendered .github/ISSUE_TEMPLATE/feature_request.md](https://github.com/aio-libs/aiohttp/blob/llhttp-3.8/.github/ISSUE_TEMPLATE/feature_request.md)
[View rendered .github/PULL_REQUEST_TEMPLATE.md](https://github.com/aio-libs/aiohttp/blob/llhttp-3.8/.github/PULL_REQUEST_TEMPLATE.md)

### CODE REVIEW

**Comment by webknjaz** [comment]
pre-commit.ci run

**Comment by webknjaz** [comment]
For some reason, the GHA workflows didn't get triggered. I'll try re-opening this. It looks like a platform problem on the GH side but their status page is green at the moment.

**Comment by webknjaz** [comment]
Looks like that helped.

**Comment by asvetlov** [comment]
Let's close until the master is green

**Pull request closed without merging**
