### PR TITLE
correct filename in content-disposition with multipart body

### PR DESCRIPTION
**Pull request by samuelcolvin**
## What do these changes do?

Correct filename in content-disposition with multipart body, also improve coverage.

## Are there changes in behavior for the user?

Filename will be correct where previously it used the part's name.

## Related issue number

#3064

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] Add a new news fragment into the `CHANGES` folder

### CODE REVIEW

**Comment by samuelcolvin** [comment]
trying to fix tests now.

**Comment by asvetlov** [comment]
Heh, windows bot fails.
I suggest using `tmpdir` fixture instead.

**Comment by asvetlov** [comment]
Network issue on Travis side.
I've restarted jobs.

**Comment by asvetlov** [comment]
Cool!
Everything is passed.

**Pull request merged**
