### PR TITLE
Improve startup cleanup signals

### PR DESCRIPTION
**Pull request by cecton**
## What do these changes do?

1. cleanup signal is sent even if startup signal failed
2. ~helpers to create and manage background tasks~

## Are there changes in behavior for the user?

1. The cleanup hooks will be called more often at the end of the process. You now try to connect to a database in a startup hook and get your client session cleaned automatically in the cleanup even if the database connection failed.
2. ~You no longer need to use the dict methods of Application to create tasks to manage background processes, you can use the helper `add_task` and provide a coroutine. The coroutine will be called with the app argument. When the application finishes, the tasks will be cancelled and awaited properly (except if a task raise SystemExit or any not Exception based exception).~

## Related issue number

#2092 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `changes` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by cecton** [comment]
@asvetlov  I tested on 3.4.6, 3.5.3, 3.6.0 and 3.6.1 and it works. Unfortunately asyncio is a bit different in 3.4.3 and 3.4.2. Do you really want to support those specific versions?

**Comment by cecton** [comment]
(In 3.4.4 it works already)

**Comment by cecton** [comment]
@asvetlov last one but biggest one. You can maybe cherry pick ca5fb94 separately if the rest doesn't meet your expectations.

**Comment by asvetlov** [comment]
Hmm. I definitely don't want `app.add_task()` and others.
People was reluctant for incorporating `aiojobs`, your proposal overlaps with the library a little bit.
Could you make a PR for ca5fb94 only?
I can cherry-pick it but prefer well-formed pull requests :)

**Comment by cecton** [comment]
@asvetlov done! I will check aiojobs later to see if I can replace some code in my projects.

Besides I think it's still confusing, the documentation says that you can spawn background processes in that fashion: http://aiohttp.readthedocs.io/en/stable/web.html#background-tasks

It mostly works but it is not perfect, there is a little bit more to do to get a background job working, logging and terminating properly.

If people find that aiohttp should not handle background jobs at all, then it would make more sense to remove this example of the documentation.

If background jobs are okay, then we should either give an example that works perfectly or implement the helpers like I did (my helpers are still 37 lines of code in Application (still smaller than aiojobs).

**Comment by asvetlov** [comment]
Docs should be updated, sure.
Let's left this task to other PR.

Regarding to this one I think we need mention the behavior in docs too both in Usage and Reference.
After PR applying user should always check if her *key* is in app dict.

It is a breaking change.
On other hand we definitely don't want to have partially initialized application.
Also it correlates with #2121 a little

Mybe we need a `ServerStartUp` object with methods for saving all activities: startup signals and created handlers.
The object could be used for proper shutdown procedure.

Now it is a wild idea, let me sleep on it.

**Comment by cecton** [comment]
@asvetlov I haven't give much thought about this PR yet but I suppose we can conclude it by adding in the documentation that the startup/cleanup behavior is changed. I've just added it to the doc, I think we are good.

**Comment by asvetlov** [comment]
Better solution proposed

**Pull request closed without merging**
