### PR TITLE
Fix default `access_log_format` to correct value

### PR DESCRIPTION
**Pull request by maqquettex**
## What do these changes do?

Fixing wrong default value of access log format

## Are there changes in behavior for the user?

Should not affect anything

## Related issue number

#2649 

## Checklist

- [x] I think the code is well written
- [x] Documentation reflects the changes
- [x] Add a new news fragment into the `CHANGES` folder

### CODE REVIEW

**Comment by fafhrd91** [comment]
aiohttp uses `None` for specific reason. enabled server logging significantly reduce performance even if logging it self is not enabled.

**Comment by azhpushkin** [comment]
Problem of this PR is more about having bad parameters, I tried to describe everything in details in the issue. 
Access logger is enabled while default argument of class is set (`access_logger` is not False). I could  set it to None in this PR also, however this is another story so I would like to leave it the way it is .

**Comment by fafhrd91** [comment]
drop performance by 20% is not good change, especially for default parameters.

**Comment by azhpushkin** [comment]
@fafhrd91 Sorry, maybe I`m not following something but with current default params for me views are not working at all. Access logger is being initialized for each request in the following part of code:
https://github.com/aio-libs/aiohttp/blob/19c138c864adb37823c4723901a9b84bd2197085/aiohttp/web_protocol.py#L135-L139

As access logger over here is True `access_log_class(...)` is called. Afterwards, default [AccessLogger.__init__](https://github.com/aio-libs/aiohttp/blob/19c138c864adb37823c4723901a9b84bd2197085/aiohttp/helpers.py#L264) is called, than compile_format() is called and it fails in the following line:
https://github.com/aio-libs/aiohttp/blob/19c138c864adb37823c4723901a9b84bd2197085/aiohttp/helpers.py#L352

This is happening because log_format over here is None. 
Also there is no exception or traceback being produced before loop is closed. Can you please try Steps to reproduce to see whether you getting this problem too?

**Comment by fafhrd91** [comment]
you are right, sorry. somehow I thought that access log is disabled by default.

**Comment by asvetlov** [comment]
Access log was enabled by default in aiohttp 2.x
The issue is a result of my refactoring for `AppRunner`, I forgot to set proper default value.

**Comment by asvetlov** [comment]
Thanks

**Pull request merged**
