### PR TITLE
Add deprecation warning when HTTPException is returned instead of raised

### PR DESCRIPTION
**Pull request by panagiks**
## What do these changes do?

Add DeprecationWarning when an HTTPException is returned instead of being raised.

## Are there changes in behavior for the user?

If user's handler (view function) returns an HTTPException, a DeprecationWarning will be displayed.

## Related issue number

Discussion in #2415

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by asvetlov** [comment]
Sorry, travis checks is broken by me.
Will fix it soon.

**Comment by panagiks** [comment]
[INVALID QUESTION] I will add the build_response() method along with test in a while. Do we need reference to HTTPException instance in Response? (should I instantiate the object as done in [HTTPException's constructor](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_exceptions.py#L79) or by `Response(...)`)

**Comment by panagiks** [comment]
I'm not really a fan of the implementation in my last commit (as it includes some code repetition) but there were a few issues with my initial approach:
* If build_response() creates a new Response there is the issue that, at this point, self.body and self.text are already both populated and this fails [this check](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_response.py#L448). Similarly content_type is present along with a Content Type header that fails [this check](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_response.py#L463).
* Removing the inheritance of Response (so the above values don't get populated during HTTPException initialization) is, as you noted, too invasive, as a few aiohttp components along the way depend on it's behaviour as both Response and Exception.

If there are any suggestions for a better approach I'd be more than happy to implement them :)

**Comment by panagiks** [comment]
I also thought about returning `self` in `build_response()` as self is currently a Response object. But (besides the fact that I'm not sure it would be a good practice since the target is to eventually get rid of the Response dependency) it wouldn't force middlewares to handle the non-duality of the response (i.e. functionalities that depended on response's Exception nature would still work when calling build_response(), although that feature is deprecated through the build_response() interface).

**Comment by asvetlov** [comment]
Making a new `_as_response` in constructor looks... ugly, sorry.

Let's go further.
In my mind `build_response()` should replace returning the `HTTPException` derived class.
#2521 shows my fault in changing everything at once.

But you can get the [main idea](https://github.com/aio-libs/aiohttp/pull/2521/files#diff-95ccfe4e2abcc03ee3ee36a74e6864b7L140) : `headers`, `reason`, `body`, `text` and `content_type` parameters should be deprecated.

Every class like `_HTTPMove` (a base for every `3xx` redirection response) should override `build_response()` method.

In the future (aiohttp 4.0) we need to support the only our own parameters like `location`, `link`, `allowed_methods` etc.

Sorry for long message but sure,  I've got my point.

**Comment by panagiks** [comment]
Wouldn't this change deprecate the `return web.HTTPException()` interface outright?

From #2415 I got the sense that deprecation should come in waves. i.e.:
* in one release add a deprecation warning and a new interface that you will encourage people to use (i.e. `build_response()`)
* in another release fully deprecate the `return web.HTTPException()` interface

I have no stance/opinion/position on whether the deprecation should come in waves, just the sense that I got from the issue mentioned above.

In any case, I'll look into modeling the changes needed here based on the example you provided.

Sorry for the back-and-forth this pr required and thank you for the guideline :)

**Comment by asvetlov** [comment]
I suggest merging this PR with deprecation warning only (with proper documentation update) and making a new PR for `build_response()`.

**Comment by asvetlov** [comment]
thanks!

**Pull request merged**
