### PR TITLE
List that CPython's GitHub bots are powered by aiohttp

### PR DESCRIPTION
**Pull request by Mariatta**
## What do these changes do?

Documentation update. Under "Powered by" add CPython's GitHub bots to the list.

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by asvetlov** [comment]
@Mariatta sorry, spell checker blames on `CPython` and `backports` words.
Please add them to white list: https://github.com/aio-libs/aiohttp/blob/master/docs/spelling_wordlist.txt

**Comment by webknjaz** [comment]
@asvetlov I find it very helpful that if contributor allows the maintainers can go and fix a minor nitpick themselves rather than waiting for PR author to do fix.

This might be unobvios, but *it can be done w/o leaving GitHub*: https://github.com/Mariatta/aiohttp/edit/patch-1/docs/spelling_wordlist.txt?pr=/aio-libs/aiohttp/pull/2738
;)

**Comment by asvetlov** [comment]
Really non obvious, I did not know about the way

**Comment by webknjaz** [comment]
@asvetlov you can actually hit "Edit" button on the file in PR, but for ones, which are not touched go to the author's branch in their repo and you can add/edit anything in that branch

**Comment by asvetlov** [comment]
good to know

**Comment by Mariatta** [comment]
Thanks for the quick review and merge!

**Comment by asvetlov** [comment]
Sure!

**Pull request merged**
