### PR TITLE
#4587 Always check transport is not closing before reuse

### PR DESCRIPTION
**Pull request by Dahuage**
## What do these changes do?
Always check transport is not closing before reuse a connection.

Reuse a protocol based on keepalive in headers is unreliable.
For example, uWSGI will not support keepalive even it serves a
http1.1 request, except explicitly configure uWSGI with a
`--http-keepalive` option.

Servers designed like uWSGI would cause aiohttp intermittently
raise a ConnectionResetException when the protocol poll runs
out and some protocol is reused.

Though it can be bypassed by properly configuring either in server like uWSGI or aiohttp side, this exception is confusing and annoying for new guys to aiohttp.
Yet more importantly, sometimes it can not be triggered in a development env, but it is a potential disaster when in a production env where it has high concurrence.

## Are there changes in behavior for the user?

No

## Related issue number

#4587

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by kkonevets** [comment]
@Dahuage Hi, you said one can configure properly on aiohttp side to avoid the error, how can I do it?

**Comment by Dahuage** [comment]
> @Dahuage Hi, you said one can configure properly on aiohttp side to avoid the error, how can I do it?



if the error is caused by the server you requested disable keep-alive.

then config the aiohttp send http1.0 request to the server may avoid this problem.

just init the session like this:

```
async def main():
    async with aiohttp.ClientSession(version = aiohttp.http.HttpVersion10) as sess:
        await do_sth_with_sess(sess)
```
by the way, if the server you requested is under your control, make sure your server enable HTTP/1.1 keepalive connections.

hope it helps!

**Comment by kkonevets** [comment]
@Dahuage thanks for the answer. The server is not under my control, so I just enabled http1.0, looks like it works

**Comment by IsaacFlos** [comment]
It's too cool！

**Comment by 945941192** [comment]
Thank you for your contribution to help me solve the problem for a long time.

**Comment by mncu** [comment]
wow ! cool !

**Comment by WoodyFleurant** [comment]
Seems that one test fail

**Comment by aorumbayev** [comment]
Any updates on this ?

**Comment by cdeboeser** [comment]
Would also be very interested in this fix! :) And thank you for the contribution!

**Review by asvetlov — APPROVED** [review]

**Comment by asvetlov** [comment]
Thanks!

**Pull request merged**
