### PR TITLE
http-parser -> llhttp

### LINKED ISSUE #3561: Switch http_parser to llhttp
Nodejs decide to move from their hard-coded C parser to this one.

https://github.com/nodejs/http-parser/pull/285#issuecomment-456025694

*Upd:* 
proposed parser is https://llhttp.org

### PR DESCRIPTION
**Pull request by asvetlov**
The resurrection of #5364

Closes #3561

Co-authored-by: Dmitry Erlikh <derlih@gmail.com>

### CODE REVIEW

**Comment by asvetlov** [comment]
@derlih the initial #5364 had about 8 failed tests when merged to master.
I've reverted the merge and created this PR to don't miss your work.
Not sure when I can find time to work on failed tests; my current target is publishing 3.8 with python 3.10 support, llhttp is nice to have but not mandatory.

If we cannot find time to fit in 3.8 time window -- we can publish 3.9 relatively soon, there is no need to wait another year if we will get a value soon.

P.S.
The branch is available for pushing to every aiohttp committer, feel free to help. Please don't be confused with `revert-6143-revert-5364-llhttp` branch name (revert of reversion :)

**Comment by derlih** [comment]
I've updated the `llhttp` to the latest stable and fixed the spelling error in CI

**Comment by derlih** [comment]
`test_http_request_parser_two_slashes` fails for `llhttp`. Looks line the behavior has been changed in comparison to `http_parser`.
Do we really need this test? It checks that python parser behaves the same as a native one. But this case tests wrong path with `//` inside. Also it doesn't cover many other cases with `//`. For example `llhttp` for path `//path/a` returns `/a`. Should this strange result be also implemented by python http parser and covered by tests?

Update:
This behavior is not covered by `llhttp` [tests](https://github.com/nodejs/llhttp/blob/v6.0.6/test/url.md).

**Comment by derlih** [comment]
The next problem is `aiohttp.web.normalize_path_middleware`.
This middleware has the `merge_slashes` parameter:

> If merge_slashes is True, merge multiple consecutive slashes in the path into one.

But any middleware is called after the HTTP parser. And since the behavior of double slashes in path is changed in `llhttp`, it makes sense to remove this `merge_slashes` parameter from this middleware. It's an API change -> should be shifted to the next major release.

Also I think it means that we can't have a transition phase with both native parsers at the same time.

**Comment by derlih** [comment]
Also I found that `llhttp` fixes regression #5621 :-)

**Comment by asvetlov** [comment]
> `test_http_request_parser_two_slashes` fails for `llhttp`...

We cannot change llhttp upstream (at least it requires long enough conversation I think).
But we can change the behavior of our pure-python parser to get the same result for both Python and llhttp parsing results.
Please update the failed test.

**Comment by asvetlov** [comment]
> The next problem is `aiohttp.web.normalize_path_middleware`...

If we really cannot support `merge_slashes=False` let's make the argument no-op and raise `DeprecationWarning` if `False` was passed.

**Comment by asvetlov** [comment]
> Also I found that `llhttp` fixes regression #5621 :-)

Awesome!

**Comment by asvetlov** [comment]
@derlih I think I've found the reason for broken double-slash tests.

llhttp is correct but `URL("//abc")` assumes that 'abc' is an authority, not path.
`URL.build()` should be used instead.
I'm working on it.

**Comment by derlih** [comment]
@asvetlov the middleware test is checking the [security issue](https://github.com/advisories/GHSA-v6wp-4m6f-gcjg) inside aiohttp. I don't want to reintroduce it )

**Comment by asvetlov** [comment]
I didn't touch tests except `test_http_parser.py`, where only fixture ids are added without changing the actual test code.

**Comment by asvetlov** [comment]
Tests are green, merging

**Pull request merged**
