### PR TITLE
Fix static location in index when prefix is used

### PR DESCRIPTION
**Pull request by lovebug356**
When the prefix is used (e.g. not /), the links generated in the
index page are wrong. In this patch the relative path is correctly
calculated by the pathlib module and a absolute url is used as link
in the index page.

The original bug can be demonstrated with following example:

```
import pathlib

from aiohttp import web

app = web.Application()
app.router.add_static('/static', pathlib.Path(__file__).parent,
show_index=True)

web.run_app(app)
```

### CODE REVIEW

**Comment by fafhrd91** [comment]
@asvetlov could you review this PR

**Comment by AraHaan** [comment]
Well looks good other than the posix part because it would probably jack with running aiohttp on windows?

Like I am not sure how it would interfere with how the ``\``'s are on Windows however it *should* support both ``/`` and ``\``.

**Comment by AraHaan** [comment]
Mind rebasing this PR, or reopen it?

**Comment by fafhrd91** [comment]
could you open PR against https://github.com/aio-libs/aiohttp

**Comment by AraHaan** [comment]
Seems that windows also accepts posix paths to an extent as well.

**Comment by asvetlov** [comment]
Thanks!

**Pull request merged**
