### PR TITLE
Fixed a grammatical error in documentation

### PR DESCRIPTION
**Pull request by ArionMiles**
## What do these changes do?
Fixed a grammatical mistake in documentation

### CODE REVIEW

**Comment by webknjaz** [comment]
Thanks!

**Comment by ArionMiles** [comment]
This has been merged but the documentation webpage doesn't reflect the changes, I suppose you have to rebuild the docs after merge? Do we not use post-commit hooks for auto-building the docs?

**Comment by webknjaz** [comment]
Actually it's up to RTD to rebuild those. Let me take a look at build logs...

**Comment by webknjaz** [comment]
It was successful: https://readthedocs.org/projects/aiohttp/builds/8587720/

**Comment by webknjaz** [comment]
It's here https://docs.aiohttp.org/en/latest/
Under latest URL, you see stable by default. To transfer the patch there you need to submit a backport PR against stable branch.

**Pull request merged**
