### PR TITLE
Remove Signal from __all__, replace aiohttp.Signal with aiosignal.Signal in docs

### LINKED ISSUE #6197: AttributeError: module 'aiohttp' has no attribute 'Signal'
### Describe the bug

```
Python 3.7.10 (default, May  5 2021, 13:11:39) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from aiohttp import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'aiohttp' has no attribute 'Signal'
```

### To Reproduce

```
Python 3.7.10 (default, May  5 2021, 13:11:39) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from aiohttp import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'aiohttp' has no attribute 'Signal'
```

### Expected behavior

No error. 

### Logs/tracebacks

```python-traceback
Python 3.7.10 (default, May  5 2021, 13:11:39) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from aiohttp import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'aiohttp' has no attribute 'Signal'
```

### Python Version

```console
$ python --version
3.7.10
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.0
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /Users/naoko.reeves/.pyenv/versions/3.7.10/envs/mdl-pipelines-3.7.10/lib/python3.7/site-packages
Requires: aiosignal, async-timeout, asynctest, attrs, charset-normalizer, frozenlist, multidict, typing-extensions, yarl
Required-by: pytest-aiohttp
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 5.2.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/naoko.reeves/.pyenv/versions/3.7.10/envs/mdl-pipelines-3.7.10/lib/python3.7/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.7.0
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/naoko.reeves/.pyenv/versions/3.7.10/envs/mdl-pipelines-3.7.10/lib/python3.7/site-packages
Requires: idna, multidict, typing-extensions
Required-by: aiohttp
```

### OS

macOSX

### Related component

Client

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

### PR DESCRIPTION
**Pull request by asvetlov**
Fixes #6197

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
Think we could just add a test file with `from aiohttp import *` as a regression test?

**Comment by asvetlov** [comment]
> Think we could just add a test file with `from aiohttp import *` as a regression test?

Good idea.

**Comment by asvetlov** [comment]
Backported by 3c58fc3d and 778b3340

**Comment by webknjaz** [comment]
> Think we could just add a test file with `from aiohttp import *` as a regression test?

Could go even further and check whether there's no circular imports along the way. For example, see https://github.com/sanitizers/octomachinery/blob/be18b54/tests/circular_imports_test.py (this approach is picked up from pytest).

**Comment by asvetlov** [comment]
A champion is needed.
I have no capacity for this.

**Pull request merged**
