### PR TITLE
Make web.BaseRequest and web.StreamResponse weak referenceable

### LINKED ISSUE #4368: WebSocketResponse TypeError: Cannot be put into a weakref.WeakSet
## Long story short

`WebSocketResponse` raises `TypeError` when I attempt to put it into a `weakref.WeakSet`.

## Expected behaviour

I expect to be able to do the above. This is also the [recommended graceful shutdown approach](https://github.com/aio-libs/aiohttp/blob/master/docs/web_advanced.rst#graceful-shutdown).

## Actual behaviour

I get a `TypeError`. It worked previously. It was broken by commit c6e40e78ae8de51c02b5a17b8e5e882c910d3770.

## Steps to reproduce

Just try to create a `weakref.WeakSet` and put an instance of `WebSocketResponse` in it.

## Fix

```
aiohttp/web_ws.py: Add __weakref__ to WebSocketResponse.__slots__

WebSocketResponse can now be put into a WeakSet container again.
This feature was broken by commit c6e40e78ae8de51c02b5a17b8e5e882c910d3770.

Signed-off-by: Frederik Aalund <fpa@sbtinstruments.com>

--- a/aiohttp/web_ws.py	2019-11-21 15:22:37.253377093 +0100
+++ b/aiohttp/web_ws.py	2019-11-21 15:22:40.129377093 +0100
@@ -49,7 +49,7 @@ class WebSocketResponse(StreamResponse):
                  '_closing', '_conn_lost', '_close_code', '_loop', '_waiting',
                  '_exception', '_timeout', '_receive_timeout', '_autoclose',
                  '_autoping', '_heartbeat', '_heartbeat_cb', '_pong_heartbeat',
-                 '_pong_response_cb', '_compress', '_max_msg_size')
+                 '_pong_response_cb', '_compress', '_max_msg_size', '__weakref__')

     def __init__(self, *,
                  timeout: float=10.0, receive_timeout: Optional[float]=None,
```

Some reference: https://stackoverflow.com/a/19526505/554283

## Miscellaneous

This also applies to all other classes that uses `__slots__`. I can't find a any reference to "`__weakref__`" when I search through aiohttps codebase.

## Your environment

aiohttp v4.0.0a1

### LINKED ISSUE #4370: web.Request and web.Response are no longer weak referenceable
## Long story short

https://github.com/aio-libs/aiohttp/pull/3942 added `__slots__` to request and response classes. This made it impossible to create weak references to them.
In some cases this might be useful. Example: https://github.com/getsentry/sentry-python/issues/560

Possible solution is adding `__weakref__` to `__slots__` in `web.BaseRequest` and `web.StreamResponse`.

## Expected behaviour

web.Request and web.Response to be valid targets for weak references.

## Actual behaviour

web.Request and web.Response are no longer valid targets for weak references.

## Steps to reproduce

```python
import weakref

wekref.ref(request)
# TypeError: cannot create weak reference to 'Request' object
```

### PR DESCRIPTION
**Pull request by Fogapod**
## What do these changes do?

Adding `__weakref__` to `__slots__` makes `web.BaseRequest` and `web.StreamResponse` valid targets for creating weak references.

## Are there changes in behavior for the user?

Users are able to create weak references to request and response objects again after https://github.com/aio-libs/aiohttp/pull/3942.

## Related issue number

Resolves #4368
Resolves #4370

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by Fogapod** [comment]
@asvetlov could you draft a new alpha release after this is merged? This bug causes issues on production for me, installing aiohttp from source is not easy

**Comment by untitaker** [comment]
@Fogapod I mean, you're running an alpha version of aiohttp, right?

**Comment by Fogapod** [comment]
I'm currently on `4.0.0a1`, yes

**Comment by asvetlov** [comment]
Thanks!

**Pull request merged**
