### PR TITLE
Adjust aiohttp v3.8 dep pins with `master`

### PR DESCRIPTION
**Pull request by webknjaz**
## What do these changes do?

This is an attempt to transfer/backport all of the dep pins from the `master` branch to v3.8.

## Are there changes in behavior for the user?

No.

## Related issue number

N/A

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."
(cherry picked from commit dbcf70473af2a55700782c65badc388354c78e1f)

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
> I'm curious why there are no PRs from dependabot to 3.8 branch?

There are some open ones with CI failing:
https://github.com/aio-libs/aiohttp/pulls?q=is%3Apr+is%3Aopen+dependabot

**Comment by webknjaz** [comment]
> I'm curious why there are no PRs from dependabot to 3.8 branch?

Probably because the branch is still broken. Backporting the support of Python 3.10 into the aiohttp 3.8 branch needed updating pytest. But pytest 6.2 introduces more tracking for unhandled warnings and backporting the solution for this is incomplete because some of the code that is present in 3.8 is no longer present in master so we need to also fix some of the resource and deprecation warnings additionally to those we've faced in master. Plus #6074 added dependencies that are unavailable in some of the runtimes the CI matrix has on the 3.8 branch. It's currently a very fragile set of breakages that I'm trying to untangle.

At the moment, I'm stuck with `FAILED tests/test_client_request.py::test_default_loop[pyloop]` that hits a deprecation warning under Python 3.10 because the test triggers calling `asyncio.get_event_loop()` outside of the loop and I'm not really sure what the test is supposed to do (because there's no docstring hinting why it's running this outside of a loop), and whether it's still useful.

**Comment by Dreamsorcerer** [comment]
> calling `asyncio.get_event_loop()` outside of the loop and I'm not really sure what the test is supposed to do (because there's no docstring hinting why it's running this outside of a loop), and whether it's still useful.

The test was added over 6 years ago:
https://github.com/aio-libs/aiohttp/commit/78b7e6e1dc9966e484e38a67f54c0c4da95ef5ac

It looks to me like there were no async tests back then, so it ends up outside the loop by bad luck? Converting the test to an async function may be the way to go.

**Comment by webknjaz** [comment]
> > calling `asyncio.get_event_loop()` outside of the loop and I'm not really sure what the test is supposed to do (because there's no docstring hinting why it's running this outside of a loop), and whether it's still useful.
> 
> The test was added over 6 years ago: [78b7e6e](https://github.com/aio-libs/aiohttp/commit/78b7e6e1dc9966e484e38a67f54c0c4da95ef5ac)
> 
> It looks to me like there were no async tests back then, so it ends up outside the loop by bad luck? Converting the test to an async function may be the way to go.

I'm not sure about that because it also does manipulations with the loop.

**Pull request merged**
