### PR TITLE
Patchback/backports/3.9/bd008ca646df25e043738aa85acca0d30ddcf128/pr 5898

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
Missed the backport to 3.9.

### CODE REVIEW

**Comment by webknjaz** [comment]
Looks like this is a feature and should go into the next minor release.

**Comment by Dreamsorcerer** [comment]
> Looks like this is a feature and should go into the next minor release.

i.e. 3.9? That's the target.

**Comment by Dreamsorcerer** [comment]
Test failure appears to be something already on the 3.9 branch. This PR looks good to merge.

**Comment by webknjaz** [comment]
> 

Looks like you confused the PR description, then. And that confused me.


> Test failure appears to be something already on the 3.9 branch. This PR looks good to merge.

Looks like aiohttp 3.9 now requires Python 3.7 but the PyPy version in the test matrix is still Python 3.6.

**Comment by Dreamsorcerer** [comment]
> Looks like you confused the PR description, then. And that confused me.

Yeah, sorry, I meant the backport to 3.8 was missed (it failed and nobody did a manual backport), so I'm doing the backport to 3.9 now.

> > Test failure appears to be something already on the 3.9 branch. This PR looks good to merge.
> 
> Looks like aiohttp 3.9 now requires Python 3.7 but the PyPy version in the test matrix is still Python 3.6.

Yep, just noticed that as well in #6374

**Comment by webknjaz** [comment]
Oh, it's because of https://github.com/aio-libs/aiohttp/commit/369bf7928d0a463db4805909fa69d865857b5edb.
@asvetlov — did you forget to bump the PyPy 3 version and add a changelog note?

**Comment by Dreamsorcerer** [comment]
The version in ci.yaml only specifies 'pypy3', which I assume would always pick the latest release (although I can't find any documentation confirming that). The latest release on Ubuntu-20.04 is 3.8: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#pypy

Though on Ubuntu-18.04 it's 3.6: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md#pypy

But, we appear to be asking for 'ubuntu-latest', which is supposed to be 20.04. So, I'm confused what part is misconfigured...

**Comment by Dreamsorcerer** [comment]
OK, changing to `pypy-3` gives: `Error: Invalid format of Python version for PyPy. Python version should be specified in format 'x.y'. See README for examples and documentation.` Which also matches the documentation: https://github.com/actions/setup-python#specifying-a-pypy-version

So, I think `pypy3` may be working by luck and is not the right format (possibly picking the oldest release). We'll just have to specify the minor version.

**Comment by webknjaz** [comment]
> So, I think `pypy3` may be working by luck and is not the right format (possibly picking the oldest release). We'll just have to specify the minor version.

This is the original format (that should be deprecated at some point I think) before they added support for requesting more granular versions. Something like `pypy-3.7-v7.3.3` or `pypy-3.7` would work better.

**Comment by asvetlov** [comment]
Green finally, thank you all!

**Pull request merged**
