### PR TITLE
Backport #5457

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
Improve Mypy coverage

I've skipped checking tests on this one as there are a lot of type errors coming through.

### CODE REVIEW

**Comment by webknjaz** [comment]
Looks like this needs patching...

**Comment by Dreamsorcerer** [comment]
Problem is already in the 3.8 branch (see failed tests on last commit to 3.8).

It looks like the `CIMultiDictProxy[str]` syntax should work because of this code:
https://github.com/aio-libs/multidict/blob/master/multidict/_abc.py#L7

Is it possible that the functionality is missing from the C version?
https://github.com/aio-libs/multidict/blob/master/multidict/_multidict.c

Or any other ideas @webknjaz?

**Comment by Dreamsorcerer** [comment]
Problematic annotation was added in: https://github.com/aio-libs/aiohttp/commit/383016b4f9b88b5eaf02f4bf649248827210dd24#diff-197153342549adb4b25580f8b842876841eec42dc48ae12cb72ba2ae4f7ced10R79

I can annotate it another way if needed, but I'd expect it to work if the class supports `__getitem__`

**Comment by webknjaz** [comment]
Dunno, maybe quote it?

**Comment by derlih** [comment]
I've created the PR #5448 to fix the problem on a CI. But I don't know how to solve the mypy issue there :-(

**Pull request merged**
