### PR TITLE
Add name and backref to add_subapp

### PR DESCRIPTION
**Pull request by heckad**
## What do these changes do?

This pull request adds to add_subapp method two new optional arguments wich make code more cliar.

Example:
  before
```
    subapp = create_api_app()
    _app.add_subapp('/api', subapp)
    _app['api'] = subapp
    subapp['parent_app'] = _app
```
  after
```
  _app.add_subapp('/api', create_api_app(), name='api', backref='parent_app')
```

If this good change, I will do next steps.

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by heckad** [comment]
Maybe need to add `subapp` storage for solving problems with name intersection, but it can make pipe more complex. 
For example:

before:
 `app['api']['v1.0'].router['status']`
after:
 `app.subapps['api'].subapps['v1.0'].router['status']`

**Comment by asvetlov** [comment]
Can it be implemented by a third-party helper without modifying aiohttp core code?
Sure!
Is the feature useful for the vast majority of code that is built with aiohttp.web?
I very doubt. I use subapps extensively at my daily job, we never needed such functionality.
This is the first request I ever recall for aiohttp 6 years old history.

**Comment by heckad** [comment]
> Can it be implemented by a third-party helper without modifying aiohttp core code?
> Sure!

We noticed that you are going to make an application class is final and add `__init_subclass__` warning. Now we inherit from the application class and override some methods. In future, we can't do this and should use composition or use procedure programming (make a function for this logic). Therefore we offer this function in the base code.

> Is the feature useful for the vast majority of code that is built with aiohttp.web?
> I very doubt. I use subapps extensively at my daily job, we never needed such functionality.
> This is the first request I ever recall for aiohttp 6 years old history.

Do you never store app in app storage? You add a special comment for this case in [fac](https://docs.aiohttp.org/en/stable/web_advanced.html#nested-applications)

**Comment by asvetlov** [comment]
Maybe because my sub-applications are isolated good enough, the reverse URL lookup is almost never needed. Well, it may depend on the sort of developed application.
Maybe in your case you need the lookup constantly, and this is fine.
 
Anyway, you can write a custom top-level function that does everything that you want.

**Comment by heckad** [comment]
In this case useing nested apps not the same as using bluprints. Does aiohttp have bluprints concept in future?

**Comment by asvetlov** [comment]
What is the blueprint concept in your mind?
How backref converts sub-application into a blueprint?
Why do you think that blueprints are necessary?

I have a feeling that you are asking about *something* without the feature definition. Sorry, brainreading is the hard skill for me.

**Pull request closed without merging**
