### PR TITLE
Run test in docker

### PR DESCRIPTION
**Pull request by derlih**
## What do these changes do?

Add new test targets to the Makefile

## Are there changes in behavior for the user?

No

## Related issue number

#6131 

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by asvetlov** [comment]
Are you committed to supporting this mode for years, adding python 3.11 etc?

I personally use  pyenv for such things:
```
cd aiohttp
pyenv install 3.10
pyenv virtualenv 3.10 aiohttp-3.10
pyenv local aiohttp-3.10
```
`pyenv local ...` call can be used for switching aiohttp environments.
Maybe this approach will work for you?

**Comment by webknjaz** [comment]
I'm also not sure I'd want to support yet another test invocation method. Using pyenv is more than enough normally.

**Comment by derlih** [comment]
This mode would be only used by people who contribute to aiohttp. If such a person sees that a new python version is missing, they can just add with a couple of lines, isn't it?

**Comment by derlih** [comment]
@asvetlov with backporting to 3.8?

**Comment by asvetlov** [comment]
Up to you. Probably having the PR backported can be handy

**Pull request merged**
