### PR TITLE
fix a TypeError where MultiDict keys should be either str or subclass…

### PR DESCRIPTION
**Pull request by rschalch**
fix a TypeError where MultiDict keys should be either str or subclass str

### CODE REVIEW

**Comment by asvetlov** [comment]
But `field.name` is always a string, isn't it?

**Comment by rschalch** [comment]
@asvetlov I was able to capture this output from a default pytest call:
```
Traceback (most recent call last):
  File "/home/rbs/Projects/aiohttp/aiohttp/web_protocol.py", line 416, in start
    resp = yield from self._request_handler(request)
  File "/home/rbs/Projects/aiohttp/aiohttp/web.py", line 323, in _handle
    resp = yield from handler(request)
  File "/home/rbs/Projects/aiohttp/tests/test_client_functional.py", line 1439, in handler
    data = await request.post()
  File "/home/rbs/Projects/aiohttp/aiohttp/web_request.py", line 569, in post
    out.add(field.name, value)
  File "multidict/_multidict.pyx", line 385, in multidict._multidict.MultiDict.add
  File "multidict/_multidict.pyx", line 346, in multidict._multidict.MultiDict._add
  File "multidict/_multidict.pyx", line 270, in multidict._multidict._str
TypeError: MultiDict keys should be either str or subclasses of str
```

**Comment by asvetlov** [comment]
What is your web form and it values?

**Comment by rschalch** [comment]
Sorry, that's a sign that if different values are passed to form, the validation was not supposed to be where I put them, I will close this PR.

**Pull request closed without merging**
