### PR TITLE
Update Third-Party libraries

### PR DESCRIPTION
**Pull request by jamespeterschinner**
## What do these changes do?

Fixed typo in Docs. 
Added async-v20 to Third-Party libraries -> Others

## Are there changes in behavior for the user?

No

## Related issue number

N/A

## Checklist

- [X ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by webknjaz** [comment]
Your branch is messed up

**Comment by webknjaz** [comment]
Please fix the mess with the branch and recreate a clean PR with only your changes there.

**Comment by jamespeterschinner** [comment]
Excuse the ignorance.  But, how did I mess up the branch's? Was it that I forked master not 2.3?

**Comment by webknjaz** [comment]
It's just that 2.3 is for bugfixes and master is a trunk you combined two branches, which led to 130 commits (tons of unrelated changes) in this PR. But your new PR is just perfect, thanks :)

**Comment by jamespeterschinner** [comment]
Ops, thanks for the explanation!

**Pull request closed without merging**
