### PR TITLE
Document client error response fields

### PR DESCRIPTION
**Pull request by zackhsi**
## What do these changes do?

This change documents ClientResponseError fields code, message, and headers.

## Are there changes in behavior for the user?

No.

## Related issue number

N/A.

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by hellysmile** [comment]
What the there reason to update so old version of docs?

**Comment by zackhsi** [comment]
@hellysmile is there a newer version of the documentation that I should point updates at instead? My intention is to update http://aiohttp.readthedocs.io/en/stable/client_reference.html?highlight=ClientResponseError#aiohttp.ClientResponseError.

**Comment by hellysmile** [comment]
Can You select master branch as target of Your pull request? aiohttp 0.21.4(Your current target) is a couple of years old

**Comment by zackhsi** [comment]
Good question. The pull request instructions said to open doc fixes to the feature branch. This branch was the only one that looked like a feature branch.

Will close and open one to master. Thanks.

**Comment by asvetlov** [comment]
The latest release is 2.3.2.
The branch for it is `2.3`: https://github.com/aio-libs/aiohttp/tree/2.3

**Pull request closed without merging**
