### PR TITLE
Hotfix #5408

### PR DESCRIPTION
**Pull request by greshilov**
## What do these changes do?

Hotfix for auto-merged #5408 
## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by greshilov** [comment]
> Also, it's not clear how well dependabot works with files included via `-r`. It may be necessary to apply pip-tools there as well.

@webknjaz 
How exactly should I implement this?

**Comment by greshilov** [comment]
I think `pip-compile` hook in `.pre-commit-config.yml` is also a good addition for checking that all dependencies are in sync.

**Comment by webknjaz** [comment]
> How exactly should I implement this?

Just have pairs of in+txt file for each

**Comment by webknjaz** [comment]
> I think `pip-compile` hook in `.pre-commit-config.yml` is also a good addition for checking that all dependencies are in sync.

Won't it always attempt to update the pins and fail the check along with unrelated changes?

**Review by webknjaz — APPROVED** [review]

**Comment by greshilov** [comment]
> > I think `pip-compile` hook in `.pre-commit-config.yml` is also a good addition for checking that all dependencies are in sync.
> 
> Won't it always attempt to update the pins and fail the check along with unrelated changes?

Fair enough.

**Pull request merged**
