### PR TITLE
Set websocket writer compression to Z_BEST_SPEED

### PR DESCRIPTION
**Pull request by bdraco**
## What do these changes do?

The performance overhead of using the defaults was
noticeable with many connections. This change
matches Nginx default.

## Are there changes in behavior for the user?

This is a noticeable performance gain with many connections
and large message sizes.  Compressed sizes will be slightly
smaller as described https://github.com/aio-libs/aiohttp/issues/2856#issuecomment-374819849

## Related issue number

https://github.com/aio-libs/aiohttp/issues/2856#issuecomment-375944162

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by bdraco** [comment]
Not sure if docs should be updated as the compression level isn't currently documented.

**Comment by bdraco** [comment]
If this is acceptable, I'll make a backport PR to 3.6 as well

**Review by asvetlov — APPROVED** [review]
LGTM, thanks!

**Comment by asvetlov** [comment]
@bdraco sorry, the time window for aiohttp 3.6 is closed.
The next release will be 3.7; I hope to publish it soon, after reviewing/merging pending pull requests.

**Pull request merged**
