### PR TITLE
Calling str() on all headers values on http_writer.writer_headers method

### PR DESCRIPTION
**Pull request by pecota**
## What do these changes do?

Just call str() on all values passed to write_headers method.

## Are there changes in behavior for the user?

Now users could pass a dict with any value to be written on the response headers.

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `changes` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by kxepal** [comment]
This looks like a way to hide user bugs. Are there any use cases for this?

**Comment by eduardompinto** [comment]
It really can be. 
I even opened that PR after making that mistake. I don't have any use cases of that.

**Comment by kxepal** [comment]
I can only recall popular request to pass numbers for numeric headers, but that's the only one and it does quite limited scope on what header values could be.

**Comment by eduardompinto** [comment]
In my code i just convert any number to a str and that worked for me. Should I close this pull request?

**Comment by kxepal** [comment]
Let's gather more opinions about for awhile.

**Comment by fafhrd91** [comment]
-1 for str()

**Comment by asvetlov** [comment]
-1 too.
Closing the issue.

**Pull request closed without merging**
