### PR TITLE
doc: added create aio app to quick start section

### PR DESCRIPTION
**Pull request by Arfey**
## What do these changes do?

I just added a short notes into documentation about `create-aio-app`.

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

screen shot 2019-02-07 at 23 23 44

### CODE REVIEW

**Comment by kxepal** [comment]
Thanks! While `create-aio-app` looks like really a web server quick start, but I think this reference should be in third_party doc since web_quickstart is about aiohttp web API itself. Unlikely you could use `create-aio-app` without knowledge of this API bits, so recommendation to use it the very start may confuse people. Especially, since that project brings quite a lot things with it.

**Comment by Arfey** [comment]
@kxepal third_party section it's as list of all libraries that will be helpful with aiohttp. I think users very rarely visit this page.
If u wanna learn some new framework u just writing a pet-project with it. u don't wanna setup your project and environment. So, `create-aio-app` will be very helpful in this stage because make setup easier.

**Comment by Arfey** [comment]
@asvetlov, thx 👍

**Comment by asvetlov** [comment]
@Arfey welcome.
BTW.
Please use literary English next time in the issue and comments but apply *ganga-brothers* style for conversations on other resources.

**Pull request merged**
