### PR TITLE
Bump vendored http-parser to v 77310ee commit

### PR DESCRIPTION
**Pull request by webknjaz**

### CODE REVIEW

**Comment by asvetlov** [comment]
@webknjaz I doubt if we should bump to not-released-yet versions of `http-parser`.
According to their log the last is 2.8.1: https://github.com/nodejs/http-parser/releases/tag/v2.8.1

**Comment by webknjaz** [comment]
Fair enough. But it has some fixes, which may be related to #3208

**Comment by asvetlov** [comment]
Which commit from http-parser unreleased master fixes #3208 ?

**Comment by webknjaz** [comment]
It seems to be https://github.com/nodejs/http-parser/commit/a7c2e8626bf6b5ddc0c891a88cb77ff9b979f006 from history, but needs verification.

**Comment by asvetlov** [comment]
Well. Let's keep the PR but avoid bumps to unreleased versions in the future.

**Comment by webknjaz** [comment]
Got it

**Comment by Swamp-Ig** [comment]
Can confirm that doing this fixed #3208

**Comment by asvetlov** [comment]
Ok, thank you

**Pull request merged**
