### PR TITLE
Drop a test that requires 1GB of memory

### PR DESCRIPTION
**Pull request by asvetlov**
This is not acceptable, sorry.
I have no choice but should drop this test entirely.
It also has a mock inside which is a bad sign -- the test doesn't test too much but the own mock.

### CODE REVIEW

**Comment by webknjaz** [comment]
@asvetlov maybe just put some marker there and never run unless explicitly asked for via command line args?

**Comment by asvetlov** [comment]
The question is: who and when will run this test?

**Comment by asvetlov** [comment]
Let me continue.
If the answer is "nobody" or "some person somehow" -- let's just drop dead code.

**Comment by webknjaz** [comment]
I think this can be useful for manual regression checks and troubleshooting with `git bisect`.

**Comment by webknjaz** [comment]
Also, if we're going for multiple CIs it could be run on unimportant ones only or maybe only on nightlies.

**Comment by asvetlov** [comment]
Agree in general but not for this particular case.
I can imagine a real test that requires a lot of memory or network resources.
But this case is all about mocking.
It is very subtle itself but requires 1GB RAM. Do you feel a bad smell?

**Comment by webknjaz** [comment]
Okay, I can relate to that.

**Pull request merged**
