### PR TITLE
Contributor added

### PR DESCRIPTION
**Pull request by Siddheshwar-goodBoy**
## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by asvetlov** [comment]
Please recall me what is your contribution?
A link to commit would be awesome!

**Comment by frenck** [comment]
@asvetlov It is a new account, spamming PR's for Hacktoberfest. My recommendation would be closing it and adding an `invalid` label to it (Hacktoberfest processes those `invalid` labels to invalidate the contributions).

Closed PR on our end as well (some other projects did as well).

**Comment by asvetlov** [comment]
Done.
Thanks, @frenck

**Comment by samuelcolvin** [comment]
maybe worth reporting the user to stop others having this problem?

**Comment by asvetlov** [comment]
@samuelcolvin up to you

**Comment by samuelcolvin** [comment]
done.

**Comment by webknjaz** [comment]
FYI the official way of reporting such PRs is setting that `invalid` label.

**Pull request closed without merging**
