### PR TITLE
Wrap open_connection for ssl exceptions.

### PR DESCRIPTION
**Pull request by hellysmile**
## What do these changes do?

Work in progress for https://github.com/aio-libs/aiohttp/issues/2408

## Are there changes in behavior for the user?

ssl related errors raise aiohttp ssl exception instead of plain ssl exceptions

## Related issue number

https://github.com/aio-libs/aiohttp/issues/2408

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `changes` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by asvetlov** [comment]
Looks good. Please let me know when you finish.

**Comment by hellysmile** [comment]
@asvetlov I've added tests for ssl related errors, but they are little bit 'tricky'. It is very complex to mock `loop.create_connection` 2 time different for same `yield from` statement. I've tried to use `Mock.return_value = [case1, case2]` but it is even more complex cuz `Mock` can not be yielded.

As well here was fixed conversion from `OSError` to `ClientConnectorError` during `_resolve_host`

**Comment by hellysmile** [comment]
If needed I can move fix for `OSError to ClientConnectorError` to different pull request

**Comment by hellysmile** [comment]
I've extracted dns fix to https://github.com/aio-libs/aiohttp/pull/2430 , which is needed to be merged before this fix

**Comment by hellysmile** [comment]
Should be merged in 2.3 branch https://github.com/aio-libs/aiohttp/pull/2446

**Pull request closed without merging**
