### PR TITLE
add more types to LooseCookies #4205

### LINKED ISSUE #4205: The definition of LooseCookies is too narrow
Seems both `CookieJar.update_cookies()` and `ClientRequest.update_cookies()` accept also `Iterable[Tuple[str, Union[Morsel, str]]` and `Mapping[str, Union[Morsel, str]]`.

The definition of `LooseCookies` which does not include the above types is not compatible with existing user code.

### PR DESCRIPTION
**Pull request by AtomsForPeace**
## What do these changes do?

They add two new types to the Union for LooseCookies

I don't think it looks very pretty. Maybe it should be handled differently like define types for each of the possible options in the union. What do you think?

## Are there changes in behavior for the user?

No, just type checking

Fixes  #4205

 
There are no changes in behavior for the user
## Checklist
* [x]  I think the code is well written
* [x]  Unit tests for the changes exist
* [x]  Documentation reflects the changes
* [ ]  If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is <Name> <Surname>.
  * Please keep alphabetical order, the file is sorted by names.
 * [x]  Add a new news fragment into the `CHANGES` folder
   * name it `<issue_id>.<type>` for example (588.bugfix)
   * if you don't have an `issue_id` change it to the pr id after creating the pr
   * ensure type is one of the following:
       * `.feature`: Signifying a new feature.
       * `.bugfix`: Signifying a bug fix.
       * `.doc`: Signifying a documentation improvement.
       * `.removal`: Signifying a deprecation or removal of public API.
       * `.misc`: A ticket has been closed, but it is not of interest to users.
   * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by AtomsForPeace** [comment]
I had removed the checklist by mistake... Added it again. Can you run the checks again please?

**Comment by webknjaz** [comment]
@AtomsForPeace that's about adding a change fragment to https://github.com/aio-libs/aiohttp/tree/master/CHANGES

**Comment by AtomsForPeace** [comment]
> @AtomsForPeace that's about adding a change fragment to https://github.com/aio-libs/aiohttp/tree/master/CHANGES

Thanks for the hint! I've added one now

**Comment by asvetlov** [comment]
Thanks!

**Pull request merged**
