### PR TITLE
Fix websocket client should stopped without returning stop marker to user when get an EofStream.

### PR DESCRIPTION
**Pull request by thomaszdxsn**
…user when get an EofStream.

## What do these changes do?

If `ClientWebSocketResponse.receive()` raise a `EofStream`, should not return it to user, just stop iteration.

## Are there changes in behavior for the user?

use `asyn for` in ClientWebSocketResponse will not get a EofStream.

## Related issue number

#2784 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by asvetlov** [comment]
I suspect server websocket has the same behavior.
Could you take a look?

**Comment by thomaszdxsn** [comment]
ok, i will do that in weekend

**Comment by asvetlov** [comment]
NP. Feel free to ask here or use https://gitter.im/aio-libs/Lobby chat.
I'll happy to help (when I'm available online).

**Comment by thomaszdxsn** [comment]
I think it's ok, please review it.

**Comment by asvetlov** [comment]
Don't want making 3.0.X bugfix release since we are in preparing to 3.1.0.
I expect to get it in a few days.

**Pull request merged**
