### PR TITLE
Forward arbitrary kwargs from web.run_app to the runner

### PR DESCRIPTION
**Pull request by filmor**
## What do these changes do?

Allow modifying the behaviour of the `AppRunner` instance, in particular of the underlying HTTP parser.

## Are there changes in behavior for the user?

Not unless this is used explicitly.

## Related issue number

-/-

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by asvetlov** [comment]
# [Codecov](https://codecov.io/gh/aio-libs/aiohttp/pull/4588?src=pr&el=h1) Report
> Merging [#4588](https://codecov.io/gh/aio-libs/aiohttp/pull/4588?src=pr&el=desc) into [master](https://codecov.io/gh/aio-libs/aiohttp/commit/b444ff58a712bf796b8795380081449303a80b37&el=desc) will **decrease** coverage by `1.37%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/aio-libs/aiohttp/pull/4588?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master    #4588      +/-   ##
==========================================
- Coverage   97.57%   96.20%   -1.38%     
==========================================
  Files          43       43              
  Lines        8907     8878      -29     
  Branches     1404     1393      -11     
==========================================
- Hits         8691     8541     -150     
- Misses         96      204     +108     
- Partials      120      133      +13     
```


| [Impacted Files](https://codecov.io/gh/aio-libs/aiohttp/pull/4588?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [aiohttp/web\_fileresponse.py](https://codecov.io/gh/aio-libs/aiohttp/pull/4588/diff?src=pr&el=tree#diff-YWlvaHR0cC93ZWJfZmlsZXJlc3BvbnNlLnB5) | `78.80% <0.00%> (-19.03%)` | :arrow_down: |
| [aiohttp/pytest\_plugin.py](https://codecov.io/gh/aio-libs/aiohttp/pull/4588/diff?src=pr&el=tree#diff-YWlvaHR0cC9weXRlc3RfcGx1Z2luLnB5) | `91.83% <0.00%> (-5.60%)` | :arrow_down: |
| [aiohttp/web\_runner.py](https://codecov.io/gh/aio-libs/aiohttp/pull/4588/diff?src=pr&el=tree#diff-YWlvaHR0cC93ZWJfcnVubmVyLnB5) | `92.47% <0.00%> (-5.31%)` | :arrow_down: |
| [aiohttp/http\_parser.py](https://codecov.io/gh/aio-libs/aiohttp/pull/4588/diff?src=pr&el=tree#diff-YWlvaHR0cC9odHRwX3BhcnNlci5weQ==) | `91.72% <0.00%> (-4.70%)` | :arrow_down: |
| [aiohttp/helpers.py](https://codecov.io/gh/aio-libs/aiohttp/pull/4588/diff?src=pr&el=tree#diff-YWlvaHR0cC9oZWxwZXJzLnB5) | `92.70% <0.00%> (-3.91%)` | :arrow_down: |
| [aiohttp/http\_writer.py](https://codecov.io/gh/aio-libs/aiohttp/pull/4588/diff?src=pr&el=tree#diff-YWlvaHR0cC9odHRwX3dyaXRlci5weQ==) | `95.28% <0.00%> (-3.78%)` | :arrow_down: |
| [aiohttp/tcp\_helpers.py](https://codecov.io/gh/aio-libs/aiohttp/pull/4588/diff?src=pr&el=tree#diff-YWlvaHR0cC90Y3BfaGVscGVycy5weQ==) | `90.00% <0.00%> (-3.34%)` | :arrow_down: |
| [aiohttp/worker.py](https://codecov.io/gh/aio-libs/aiohttp/pull/4588/diff?src=pr&el=tree#diff-YWlvaHR0cC93b3JrZXIucHk=) | `94.11% <0.00%> (-2.53%)` | :arrow_down: |
| [aiohttp/connector.py](https://codecov.io/gh/aio-libs/aiohttp/pull/4588/diff?src=pr&el=tree#diff-YWlvaHR0cC9jb25uZWN0b3IucHk=) | `94.02% <0.00%> (-2.27%)` | :arrow_down: |
| [aiohttp/web\_protocol.py](https://codecov.io/gh/aio-libs/aiohttp/pull/4588/diff?src=pr&el=tree#diff-YWlvaHR0cC93ZWJfcHJvdG9jb2wucHk=) | `91.52% <0.00%> (-1.17%)` | :arrow_down: |
| ... and [7 more](https://codecov.io/gh/aio-libs/aiohttp/pull/4588/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/aio-libs/aiohttp/pull/4588?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/aio-libs/aiohttp/pull/4588?src=pr&el=footer). Last update [b444ff5...ac9fa5d](https://codecov.io/gh/aio-libs/aiohttp/pull/4588?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by hyzyla** [comment]
Looks like there was similar PR https://github.com/aio-libs/aiohttp/pull/3861

**Comment by filmor** [comment]
Well, yes, this was meant to fix the exact same issue. Right now I have to monkey-patch `aiohttp` in production to be able to handle Kerberos auth headers...

Is there anything you want me to do to progress this?

**Comment by hyzyla** [comment]
> I think we should go in the opposite direction: get rid of `**kwargs`` usage but enumerate and pass all parameters explicitly.

I agree with the comment from asvetlov on how the solution to this problem can be. You can provide an explicit keyword argument to web.run_app instead of `**kwargs`

**Comment by asvetlov** [comment]
The idea is good but shuld be implemented (and documented) by explicit passing any desired argument

**Pull request closed without merging**
