### PR TITLE
Correct request.app context (for handlers not just middlewares)

### PR DESCRIPTION
**Pull request by popravich**
This is an update to #2550 
`_fix_request_current_app` middleware was added if application had any middlewares.
Now it is yielded unconditionally to set proper context for handlers as well.

### CODE REVIEW

**Comment by popravich** [comment]
@asvetlov , I'm not sure about target branch — should it be master or some bugfix branch?

**Comment by asvetlov** [comment]
I'll cherry-pick to 2.3 myself

**Comment by asvetlov** [comment]
thanks!

**Comment by pfreixes** [comment]
Just FYI this fix impacted with a loss btw 5%-10% of the performance, we should try to make it in some way that does not reuse the middlewares code to setup also the current app when there are no middlewares installed.

**Comment by amirouche** [comment]
Does it make sens to optimize for the case where there is no middleware?

**Comment by asvetlov** [comment]
The check should analyze not only middlewares but nested applications also.
Pull Request is welcome!

**Comment by popravich** [comment]
The performance loss might be introduced by making `Request.app` a real property and not cached one.
So I guess optimizing for the case when there are no middlewares might not bring those percents back.

**Pull request merged**
