### PR TITLE
Client response

### PR DESCRIPTION
**Pull request by penguinolog**
## What do these changes do?

Attach request_info to response object

## Are there changes in behavior for the user?

Possible to get request url and headers from response object.

## Related issue number

#1705

### CODE REVIEW

**Comment by fafhrd91** [comment]
could you modify `ClientResponseError` and add request_info to this exception in `raise_for_status`

**Comment by penguinolog** [comment]
Ok, I'll do it tomorrow.

**Comment by fafhrd91** [comment]
Awesome

**Comment by penguinolog** [comment]
Last travis run: 1 job fail was produced by different reason (asyncio failure).

**Comment by fafhrd91** [comment]
awesome! thanks

**Pull request closed without merging**
