### PR TITLE
traditional read_timeout implementation

### PR DESCRIPTION
**Pull request by thehesiod**
First hack at implementing the traditional implementation of read_timeout support.  It layers upon the current implementation.

I also added a note that the current impl of read_timeout is not quite correct as it really should be implemented as a pool of time that is pulled from when waiting for data from the server, instead of a fixed timeout from when the request is started as it doesn't take into account how the client uses the API.

attempts to fix https://github.com/aio-libs/aiohttp/issues/1954

### CODE REVIEW

**Comment by thehesiod** [comment]
ok, this is my first implementation, @fafhrd91  let me know what you think.  It is kinda hacky...if I were to do it nicer I would completely re-do how timeouts are handle to make it a pool of time that is drawn from when we're waiting for data from the server, but that's a much bigger change.  Also a nicer impl would probably pass the read_timeout across the http parser and to the stream class.

**Comment by fafhrd91** [comment]
Complexity for nothing. I don't like idea in first place. If everyone agrees then we need to redesign feature from the ground.

@asvetlov @kxepal

**Comment by thehesiod** [comment]
I still don't understand how you don't see this a a critical feature.  The primary use case is you want to guard against a server that has hung (think of FTP use case).  The current impl requires the client to calculate how long the request will take based on your current network conditions, size of file, and load. Furthermore, in the case of a large file, you'll probably sent the timeout to something like 5 minutes, this means it will take you 5 minutes to detect that a server has hung instead of the 2s it takes to receive a chunk and detect the hang. This also means you would have to have different times for different sized files.  Further like I've mentioned before several times network read_timeouts are traditionally handled the way I've mentioned, if you wanted a total timeout it should not have been called read timeout, instead it should have been called request timeout or something else.

**Comment by fafhrd91** [comment]
what is wrong with with code?
```python

with async_timeout.timeout(1):
    session.get()
```

**Comment by thehesiod** [comment]
that doesn't affect reading to body of the respose, how would you propose detecting a body read timing out?

**Comment by fafhrd91** [comment]
```python

with Timeout(1):
    resp = yield from session.get()

with Timeout(2):
   content = yield from resp.read()

with Timeout(3):
   chunk = yield from resp.content.read_any()
```

**Comment by thehesiod** [comment]
ya, vs: `async with aiohttp.ClientSession(conn_timeout=1, read_timeout=(1, None)) as session` with my impl, much nicer no?  This works especially well with streaming responses: https://gist.github.com/thehesiod/f562d7b998eda92d4806a144f16bcf2f

If we go your route there's no point for read_timeout or conn_timeout either.  So either it should all be removed, or this enhancement added IMHO.

**Comment by thehesiod** [comment]
libraries should make clients write less code, not more code :)

**Comment by fafhrd91** [comment]
I do not want to argue anymore. -1 for this solution on top of existing one

**Pull request closed without merging**
