### PR TITLE
Changed some files to async/await syntax

### PR DESCRIPTION
**Pull request by eteamin**
issue #2350 
@asvetlov I will make the next PRs limited to 2-3 smalls files.

### CODE REVIEW

**Comment by alxpy** [comment]
I think, first you should to remove this https://github.com/aio-libs/aiohttp/blob/master/setup.py#L95

**Comment by oleksandr-kuzmenko** [comment]
I think, first you should to remove this https://github.com/aio-libs/aiohttp/blob/master/setup.py#L95 and edit this https://github.com/aio-libs/aiohttp/blob/master/setup.py#L113

**Comment by asvetlov** [comment]
Left `setup.py` changes to me.

**Comment by eteamin** [comment]
@asvetlov Is this mergable?

**Comment by eteamin** [comment]
CI seems to be good :)

**Comment by asvetlov** [comment]
thanks!

**Pull request merged**
