### PR TITLE
Update db preparation script

### PR DESCRIPTION
**Pull request by gyermolenko**
This PR does the following:

- Create `init_db.py` script to create tables via sqlalchemy according to existing models and not recreate them with raw sql (replacement for `create_tables.sql` and, consequently, for `install.sh`).

- fix db config initialization
- fix title in `results.html`
    
If/when it merges I could update `Database schema` part of tutorial documentation

### CODE REVIEW

**Comment by asvetlov** [comment]
@gyermolenko would you take a look on #1443 first?

I really want to have it implemented before working on this PR.

Next topic is: @jettify used simple SQL scripts instead of `alembic` tool for sake of simplicity.
But if we want to move ahead a proper demonstration of alembic usage is better maybe?

**Comment by gyermolenko** [comment]
Ok, no problem )
I will take a look at trafaret (and try to apply it for polls). Never heard of it before. 
Alembic is also a good idea, I will think about it.

**Comment by asvetlov** [comment]
Please split tasks 
`trafaret_config` first and `alembic` later.
For saving your time please discuss the need for alembic first.

**Comment by gyermolenko** [comment]
Split tasks - sure.
As for "discuss the need for alembic" - where/with who?

**Comment by jettify** [comment]
In `aiohttp_admin` demos  I end up with fake data generating script + docker-compose file (https://github.com/aio-libs/aiohttp_admin/blob/master/demos/polls/aiohttpdemo_polls/generate_data.py). Having only docker it is easy to get demo running. 
```
make docker_start_pg
make fake_data
make run
```
and no more fighting with postgres user/permission configuration.

**Comment by jettify** [comment]
+1 for `alembic` it will be very useful.

**Comment by popravich** [comment]
-1 for alembic — it has its own tutorials.
polls demo db is quite simple and can be initialized from python (or shell) script.

**Comment by jettify** [comment]
depends what is our goal, we want to show simple project as a demo of aiohttp related features? or we want full feature project to show users how to organize code in the project?

**Comment by gyermolenko** [comment]
For the sake of comparison with other tutorials: 
- Django uses native migrations
- Flask ([Flaskr app](http://flask.pocoo.org/docs/0.11/tutorial/dbinit/)) doesn't use migrations (and no models.py or alike)
- [Flask mega tutorial](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-iv-database) uses SQLAlchemy-migrate, although this part was written in 2012.

**Comment by popravich** [comment]
> depends what is our goal, we want to show simple project (**A**) as a demo of aiohttp related features? or we want full feature (**B**) project to show users how to organize code in the project?

IMHO:
I'm for **A** — less code to learn in example — faster to start. And it's more kinda *aiohttp demo* not *how to code demo*...
**B** can be an option for separate set of tutorials

**Comment by AraHaan** [comment]
So, is this still being worked on or not? Also is this even needed anymore? @fafhrd91 @asvetlov mind letting me know if this is really needed anymore now that a lot of things has changed since then?

**Comment by asvetlov** [comment]
Sorry, but I'm closing the PR.
Subprocess calls for DB tables creation is bad practice I believe.
Better to leave the demo as is -- people will learn about db setup etc. anyway

**Pull request closed without merging**
