### PR TITLE
add secure_proxy_ssl_header to Application init

### LINKED ISSUE #1762: secure_proxy_ssl_header with gunicorn
## Long story short

I think it's not possible to set `secure_proxy_ssl_header` when deploying with gunicorn.

## Expected behaviour

gunicorn config or environment variable should allow me to set `secure_proxy_ssl_header='X-Forwarded-Proto'` so `request.scheme` is correct.

## Actual behaviour

No apparent way to set it.

## Steps to reproduce

Can give more detail if required.

## Your environment

Heroku, but should be the same with any other.

### PR DESCRIPTION
**Pull request by samuelcolvin**
fix #1762

### CODE REVIEW

**Comment by fafhrd91** [comment]
whats about 'X-Forwarded-Proto' header? should we check for it as well?

**Comment by samuelcolvin** [comment]
you mean on `.secure`? I thought `.scheme` already did that?

**Comment by fafhrd91** [comment]
oh, np. I missed code in _schema

**Comment by fafhrd91** [comment]
could you fix spelling in web_reference, 

https://travis-ci.org/aio-libs/aiohttp/jobs/224700291

**Comment by fafhrd91** [comment]
btw do we need special treatment for "wss:" ?

**Comment by samuelcolvin** [comment]
I don't think so, I assume `schema` will be `https` for `wss` (which is arguably wrong) but `secure` would then be correct.

From the docs:

> The scheme is 'https' if transport for request handling is SSL or secure_proxy_ssl_header is matching.

**Comment by fafhrd91** [comment]
ok, good.

LGTM

**Pull request merged**
