### PR TITLE
Add 'speedups' extra dependencies group

### LINKED ISSUE #2397: Design good distribution extras support
Follow-up https://github.com/aio-libs/aiohttp/pull/2312#issuecomment-339335603: this issue is intended to encourage discussion about adding extras support.

There's several optional dependencies mentioned in docs, and they instruct users to do `pip install {{dep_name}}`.

Common practice is to add feature-flags allowing to depend on certain additional ability of the framework w/o having to install those dependencies manually.

For example, aiohttp could have `speedups` extra and then user's could've just `pip install aiohttp[speedups]` instead of `pip install aiodns aiohttp cchardet`.

Also, it is possible to use environment markers as extra names, in this case certain dependencies get installed automatically if the environment matches specific expression, which might be useful for windows-only crutches etc.

Please consider treating extras as a **public API**, because they are exposed to end-users.

/cc: @asvetlov

### PR DESCRIPTION
**Pull request by webknjaz**
Resolves #2397

## What do these changes do?

Add extra deps so that it'd possible to install them along with the main project as `pip install aiohttp[speedups]`

## Are there changes in behavior for the user?

Enable users to use `pip install aiohttp[speedups]`

## Related issue number

#2397

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by kxepal** [comment]
s/speedups/faster/ - that's nicer and could be sold with easy. Also, why there is no uvloop?

**Comment by webknjaz** [comment]
I don't want `faster`, because it's a name of group of deps, not an action. It's the same as when you call a function with action/verb but you call a var/class as an object.

**Comment by webknjaz** [comment]
@asvetlov so what about `uvloop`?

**Comment by asvetlov** [comment]
Just library installation doesn't make sense, uvloop policy should be initialized by `asyncio.set_event_loop_policy()`.

I don't see a place for the call in aiohttp itself.

**Comment by webknjaz** [comment]
So I think the idea is to check whether it's present and do it on init.

**Comment by asvetlov** [comment]
What do you mean by *on init*?
I don't see any 100% reliable scenario.
A user always can do weird things, e.g. calling asyncio API **before** `aiohttp` import.
If `aiohttp` will change the default loop policy on import (which is a side effect BTW) previously opened connection will just hang etc.

**Pull request merged**
