### PR TITLE
Close unclosed client sessions properly

### PR DESCRIPTION
**Pull request by hynek**
## What do these changes do?

`ClientSession.__del__` uses a bare `self.close()` which causes a warning.  This fixes that warning.  I think this should be fine like that?

## Are there changes in behavior for the user?

One warning less.

## Related issue number

n/a

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bug)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by asvetlov** [comment]
It's a complex question.
`__del__` is called on session destruction.
It could be even interpreter finalization stage if the session has global scope (we discourage this approach but still support it).

If the loop is closed before `ClientSession.__del__` -- nothing to do.

On other hand the session could be dropped in coroutine context:
```
async def f():
    session = aiohttp.ClientSession()
    ...
    del session  # or just implicit decref on frame destruction
```   
In this case the loop is running, `loop.run_until_complete()` is prohibited.

**Comment by hynek** [comment]
Yeah, I suspected it’s not clear cut.

I’d suggest to either drop the close altogether or wrap it in a `with suppress(Exception):` for an best-effort try.  As it’s now it’s kind useless, isn’t it?

**Comment by asvetlov** [comment]
I think dropping is just fine.
Let's keep a warning report part but don't try to close the session: it is not very reliable.

**Comment by asvetlov** [comment]
Thanks!
Backported to 2.3, aiohttp 2.3.3 released

**Pull request merged**
