### PR TITLE
remove regular function usage for request handler in doc

### PR DESCRIPTION
**Pull request by thomaszdxsn**
just fix a doc typo

### CODE REVIEW

**Comment by asvetlov** [comment]
This is intentional.
A regular function support is deprecated and will be removed in aiohttp 4.0

**Comment by thomaszdxsn** [comment]
but the same doc previous line, it said `A request handler is a coroutine or regular function that accepts a Request instance as its only parameter and returns a Response instance:`, in doc `Web Server Quickstart/Run a Simple Web Server` section.

I think it is confusion.

**Comment by asvetlov** [comment]
I suggest dropping a regular function mentioning from docs everywhere to don't teach people to deprecated practices.

Would you make a PR for this?

**Comment by thomaszdxsn** [comment]
OK

**Comment by thomaszdxsn** [comment]
I found more bad example, do not merge now

**Comment by thomaszdxsn** [comment]
done

**Comment by thomaszdxsn** [comment]
Nope. Just a little thing.

**Pull request merged**
