### PR TITLE
update requirements

### PR DESCRIPTION
**Pull request by jairhenrique**

### CODE REVIEW

**Comment by asvetlov** [comment]
Dependencies are managed by PRs from https://pyup.io/ bot usually.
Also I love `pytest-sugar`. Is there any reason to drop it? Did the plugin not work on your system?

**Comment by jairhenrique** [comment]
@asvetlov no, it's just for more readability on ci output.

**Comment by asvetlov** [comment]
Hmm. We need to use `requirements/ci.txt` for travis (without pytest-sugar) and left `requirements/dev.txt` for local boxes only.

Could you dig in? When Travis install `dev.txt` requirements?
Maybe @webknjaz could help?

Anyway I suggest making a new issue to prevent the PR from blocking by this discussion

**Comment by jairhenrique** [comment]
@asvetlov I will open a new PR removing `pytest-sugar` from `ci` only.

**Pull request closed without merging**
